/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AccountDataAddress model module.
 * @module model/AccountDataAddress
 * @version 4.0.0
 */
class AccountDataAddress {
    /**
     * Constructs a new <code>AccountDataAddress</code>.
     * Full address of account owner. See below
     * @alias module:model/AccountDataAddress
     */
    constructor() { 
        
        AccountDataAddress.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AccountDataAddress</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AccountDataAddress} obj Optional instance to populate.
     * @return {module:model/AccountDataAddress} The populated <code>AccountDataAddress</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccountDataAddress();

            if (data.hasOwnProperty('street')) {
                obj['street'] = ApiClient.convertToType(data['street'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Account owner’s street address
 * @member {String} street
 */
AccountDataAddress.prototype['street'] = undefined;

/**
 * Account owner’s city
 * @member {String} city
 */
AccountDataAddress.prototype['city'] = undefined;

/**
 * Account owner’s state
 * @member {String} state
 */
AccountDataAddress.prototype['state'] = undefined;

/**
 * Account owner’s country
 * @member {String} country
 */
AccountDataAddress.prototype['country'] = undefined;






export default AccountDataAddress;

