/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AccountDataAddress from './AccountDataAddress';

/**
 * The AccountData model module.
 * @module model/AccountData
 * @version 4.0.0
 */
class AccountData {
    /**
     * Constructs a new <code>AccountData</code>.
     * Account
     * @alias module:model/AccountData
     */
    constructor() { 
        
        AccountData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AccountData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AccountData} obj Optional instance to populate.
     * @return {module:model/AccountData} The populated <code>AccountData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccountData();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('first_name')) {
                obj['first_name'] = ApiClient.convertToType(data['first_name'], 'String');
            }
            if (data.hasOwnProperty('last_name')) {
                obj['last_name'] = ApiClient.convertToType(data['last_name'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('website')) {
                obj['website'] = ApiClient.convertToType(data['website'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('company_name')) {
                obj['company_name'] = ApiClient.convertToType(data['company_name'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = AccountDataAddress.constructFromObject(data['address']);
            }
            if (data.hasOwnProperty('usage')) {
                obj['usage'] = ApiClient.convertToType(data['usage'], 'Number');
            }
            if (data.hasOwnProperty('date created')) {
                obj['date created'] = ApiClient.convertToType(data['date created'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Status of the account
 * @member {String} status
 */
AccountData.prototype['status'] = undefined;

/**
 * First name of account owner
 * @member {String} first_name
 */
AccountData.prototype['first_name'] = undefined;

/**
 * Last name of account owner
 * @member {String} last_name
 */
AccountData.prototype['last_name'] = undefined;

/**
 * Phone number of account owner
 * @member {String} phone
 */
AccountData.prototype['phone'] = undefined;

/**
 * Website of account owner
 * @member {String} website
 */
AccountData.prototype['website'] = undefined;

/**
 * Email address of account owner
 * @member {String} email
 */
AccountData.prototype['email'] = undefined;

/**
 * Account owner’s company name
 * @member {String} company_name
 */
AccountData.prototype['company_name'] = undefined;

/**
 * @member {module:model/AccountDataAddress} address
 */
AccountData.prototype['address'] = undefined;

/**
 * Account's usage
 * @member {Number} usage
 */
AccountData.prototype['usage'] = undefined;

/**
 * Account's creation time (in UTC)
 * @member {Number} date created
 */
AccountData.prototype['date created'] = undefined;






export default AccountData;

