/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The APIKey model module.
 * @module model/APIKey
 * @version 4.0.0
 */
class APIKey {
    /**
     * Constructs a new <code>APIKey</code>.
     * @alias module:model/APIKey
     */
    constructor() { 
        
        APIKey.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>APIKey</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIKey} obj Optional instance to populate.
     * @return {module:model/APIKey} The populated <code>APIKey</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIKey();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('descrption')) {
                obj['descrption'] = ApiClient.convertToType(data['descrption'], 'String');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('date_created')) {
                obj['date_created'] = ApiClient.convertToType(data['date_created'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Current status of the API key
 * @member {String} status
 */
APIKey.prototype['status'] = undefined;

/**
 * Description for API key
 * @member {String} descrption
 */
APIKey.prototype['descrption'] = undefined;

/**
 * The actual API key value
 * @member {String} key
 */
APIKey.prototype['key'] = undefined;

/**
 * Timestamp of when the API key was first created.
 * @member {String} date_created
 */
APIKey.prototype['date_created'] = undefined;






export default APIKey;

