/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ChannelData model module.
 * @module model/ChannelData
 * @version 4.0.0
 */
class ChannelData {
    /**
     * Constructs a new <code>ChannelData</code>.
     * Channel
     * @alias module:model/ChannelData
     */
    constructor() { 
        
        ChannelData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ChannelData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChannelData} obj Optional instance to populate.
     * @return {module:model/ChannelData} The populated <code>ChannelData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChannelData();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('quota')) {
                obj['quota'] = ApiClient.convertToType(data['quota'], 'Number');
            }
            if (data.hasOwnProperty('label')) {
                obj['label'] = ApiClient.convertToType(data['label'], 'String');
            }
            if (data.hasOwnProperty('usage')) {
                obj['usage'] = ApiClient.convertToType(data['usage'], 'Number');
            }
            if (data.hasOwnProperty('date_created')) {
                obj['date_created'] = ApiClient.convertToType(data['date_created'], 'Number');
            }
            if (data.hasOwnProperty('smtp_username')) {
                obj['smtp_username'] = ApiClient.convertToType(data['smtp_username'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Current status of the channel
 * @member {String} status
 */
ChannelData.prototype['status'] = undefined;

/**
 * Quota for the channel
 * @member {Number} quota
 */
ChannelData.prototype['quota'] = undefined;

/**
 * TODO FIXME
 * @member {String} label
 */
ChannelData.prototype['label'] = undefined;

/**
 * Current usage for the channel
 * @member {Number} usage
 */
ChannelData.prototype['usage'] = undefined;

/**
 * Timestamp for when the channel was originally created
 * @member {Number} date_created
 */
ChannelData.prototype['date_created'] = undefined;

/**
 * Username for the channel
 * @member {String} smtp_username
 */
ChannelData.prototype['smtp_username'] = undefined;






export default ChannelData;

