/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CreateDkimKeyData from './CreateDkimKeyData';

/**
 * The CreateDkimKey model module.
 * @module model/CreateDkimKey
 * @version 4.0.0
 */
class CreateDkimKey {
    /**
     * Constructs a new <code>CreateDkimKey</code>.
     * @alias module:model/CreateDkimKey
     */
    constructor() { 
        
        CreateDkimKey.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateDkimKey</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateDkimKey} obj Optional instance to populate.
     * @return {module:model/CreateDkimKey} The populated <code>CreateDkimKey</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateDkimKey();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = CreateDkimKeyData.constructFromObject(data['data']);
            }
        }
        return obj;
    }


}

/**
 * Request status.
 * @member {String} status
 */
CreateDkimKey.prototype['status'] = undefined;

/**
 * @member {module:model/CreateDkimKeyData} data
 */
CreateDkimKey.prototype['data'] = undefined;






export default CreateDkimKey;

