/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateDkimKeyData model module.
 * @module model/CreateDkimKeyData
 * @version 4.0.0
 */
class CreateDkimKeyData {
    /**
     * Constructs a new <code>CreateDkimKeyData</code>.
     * Domains
     * @alias module:model/CreateDkimKeyData
     */
    constructor() { 
        
        CreateDkimKeyData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateDkimKeyData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateDkimKeyData} obj Optional instance to populate.
     * @return {module:model/CreateDkimKeyData} The populated <code>CreateDkimKeyData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateDkimKeyData();

            if (data.hasOwnProperty('dkim_key')) {
                obj['dkim_key'] = ApiClient.convertToType(data['dkim_key'], 'String');
            }
        }
        return obj;
    }


}

/**
 * request result
 * @member {String} dkim_key
 */
CreateDkimKeyData.prototype['dkim_key'] = undefined;






export default CreateDkimKeyData;

