/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateDomainResponseData model module.
 * @module model/CreateDomainResponseData
 * @version 4.0.0
 */
class CreateDomainResponseData {
    /**
     * Constructs a new <code>CreateDomainResponseData</code>.
     * Domain
     * @alias module:model/CreateDomainResponseData
     */
    constructor() { 
        
        CreateDomainResponseData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateDomainResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateDomainResponseData} obj Optional instance to populate.
     * @return {module:model/CreateDomainResponseData} The populated <code>CreateDomainResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateDomainResponseData();

            if (data.hasOwnProperty('domain_name')) {
                obj['domain_name'] = ApiClient.convertToType(data['domain_name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * request result
 * @member {String} domain_name
 */
CreateDomainResponseData.prototype['domain_name'] = undefined;






export default CreateDomainResponseData;

