/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class DurationValue.
* @enum {}
* @readonly
*/
export default class DurationValue {
    
        /**
         * value: "last_hour"
         * @const
         */
        "last_hour" = "last_hour";

    
        /**
         * value: "last_day"
         * @const
         */
        "last_day" = "last_day";

    
        /**
         * value: "last_week"
         * @const
         */
        "last_week" = "last_week";

    
        /**
         * value: "last_month"
         * @const
         */
        "last_month" = "last_month";

    
        /**
         * value: "this_hour"
         * @const
         */
        "this_hour" = "this_hour";

    
        /**
         * value: "this_day"
         * @const
         */
        "this_day" = "this_day";

    
        /**
         * value: "this_week"
         * @const
         */
        "this_week" = "this_week";

    
        /**
         * value: "this_month"
         * @const
         */
        "this_month" = "this_month";

    
        /**
         * value: "last_24hrs"
         * @const
         */
        "last_24hrs" = "last_24hrs";

    
        /**
         * value: "last_7days"
         * @const
         */
        "last_7days" = "last_7days";

    
        /**
         * value: "last_30days"
         * @const
         */
        "last_30days" = "last_30days";

    
        /**
         * value: "mtd"
         * @const
         */
        "mtd" = "mtd";

    
        /**
         * value: "total"
         * @const
         */
        "total" = "total";

    
        /**
         * value: "this_year"
         * @const
         */
        "this_year" = "this_year";

    
        /**
         * value: "ytd"
         * @const
         */
        "ytd" = "ytd";

    
        /**
         * value: "last_year"
         * @const
         */
        "last_year" = "last_year";

    

    /**
    * Returns a <code>DurationValue</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/DurationValue} The enum <code>DurationValue</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

