/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetAlertDetailsData from './GetAlertDetailsData';

/**
 * The GetAlertDetails model module.
 * @module model/GetAlertDetails
 * @version 4.0.0
 */
class GetAlertDetails {
    /**
     * Constructs a new <code>GetAlertDetails</code>.
     * @alias module:model/GetAlertDetails
     */
    constructor() { 
        
        GetAlertDetails.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetAlertDetails</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetAlertDetails} obj Optional instance to populate.
     * @return {module:model/GetAlertDetails} The populated <code>GetAlertDetails</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetAlertDetails();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = GetAlertDetailsData.constructFromObject(data['data']);
            }
        }
        return obj;
    }


}

/**
 * Request status.
 * @member {String} status
 */
GetAlertDetails.prototype['status'] = undefined;

/**
 * @member {module:model/GetAlertDetailsData} data
 */
GetAlertDetails.prototype['data'] = undefined;






export default GetAlertDetails;

