/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetApiKeysData from './GetApiKeysData';

/**
 * The GetApiKeys model module.
 * @module model/GetApiKeys
 * @version 4.0.0
 */
class GetApiKeys {
    /**
     * Constructs a new <code>GetApiKeys</code>.
     * @alias module:model/GetApiKeys
     */
    constructor() { 
        
        GetApiKeys.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetApiKeys</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetApiKeys} obj Optional instance to populate.
     * @return {module:model/GetApiKeys} The populated <code>GetApiKeys</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetApiKeys();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = GetApiKeysData.constructFromObject(data['data']);
            }
        }
        return obj;
    }


}

/**
 * Request status.
 * @member {String} status
 */
GetApiKeys.prototype['status'] = undefined;

/**
 * @member {module:model/GetApiKeysData} data
 */
GetApiKeys.prototype['data'] = undefined;






export default GetApiKeys;

