/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetApiKeysDataItems model module.
 * @module model/GetApiKeysDataItems
 * @version 4.0.0
 */
class GetApiKeysDataItems {
    /**
     * Constructs a new <code>GetApiKeysDataItems</code>.
     * @alias module:model/GetApiKeysDataItems
     */
    constructor() { 
        
        GetApiKeysDataItems.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetApiKeysDataItems</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetApiKeysDataItems} obj Optional instance to populate.
     * @return {module:model/GetApiKeysDataItems} The populated <code>GetApiKeysDataItems</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetApiKeysDataItems();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('date_created')) {
                obj['date_created'] = ApiClient.convertToType(data['date_created'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Current status of the API key
 * @member {String} status
 */
GetApiKeysDataItems.prototype['status'] = undefined;

/**
 * Description for API key
 * @member {String} description
 */
GetApiKeysDataItems.prototype['description'] = undefined;

/**
 * The actual API key value
 * @member {String} key
 */
GetApiKeysDataItems.prototype['key'] = undefined;

/**
 * Timestamp of API key creation
 * @member {String} date_created
 */
GetApiKeysDataItems.prototype['date_created'] = undefined;






export default GetApiKeysDataItems;

