/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetAlertResponseDataItems model module.
 * @module model/GetAlertResponseDataItems
 * @version 4.0.0
 */
class GetAlertResponseDataItems {
    /**
     * Constructs a new <code>GetAlertResponseDataItems</code>.
     * @alias module:model/GetAlertResponseDataItems
     */
    constructor() { 
        
        GetAlertResponseDataItems.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetAlertResponseDataItems</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetAlertResponseDataItems} obj Optional instance to populate.
     * @return {module:model/GetAlertResponseDataItems} The populated <code>GetAlertResponseDataItems</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetAlertResponseDataItems();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('threshold')) {
                obj['threshold'] = ApiClient.convertToType(data['threshold'], 'String');
            }
            if (data.hasOwnProperty('alert_id')) {
                obj['alert_id'] = ApiClient.convertToType(data['alert_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * An alert’s type. Currently only “monthly_quota” is supported
 * @member {module:model/GetAlertResponseDataItems.TypeEnum} type
 */
GetAlertResponseDataItems.prototype['type'] = undefined;

/**
 * A number which represents a percentage of an account’s monthly quota. Must be decimal between 0 and 1
 * @member {module:model/GetAlertResponseDataItems.ThresholdEnum} threshold
 */
GetAlertResponseDataItems.prototype['threshold'] = undefined;

/**
 * alert ID
 * @member {String} alert_id
 */
GetAlertResponseDataItems.prototype['alert_id'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
GetAlertResponseDataItems['TypeEnum'] = {

    /**
     * value: "monthly_quota"
     * @const
     */
    "monthly_quota": "monthly_quota"
};


/**
 * Allowed values for the <code>threshold</code> property.
 * @enum {String}
 * @readonly
 */
GetAlertResponseDataItems['ThresholdEnum'] = {

    /**
     * value: "0.5"
     * @const
     */
    "0.5": "0.5",

    /**
     * value: "0.75"
     * @const
     */
    "0.75": "0.75",

    /**
     * value: "0.9"
     * @const
     */
    "0.9": "0.9",

    /**
     * value: "1"
     * @const
     */
    "1": "1"
};



export default GetAlertResponseDataItems;

