/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetCallbackLogsDataItems model module.
 * @module model/GetCallbackLogsDataItems
 * @version 4.0.0
 */
class GetCallbackLogsDataItems {
    /**
     * Constructs a new <code>GetCallbackLogsDataItems</code>.
     * @alias module:model/GetCallbackLogsDataItems
     */
    constructor() { 
        
        GetCallbackLogsDataItems.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetCallbackLogsDataItems</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetCallbackLogsDataItems} obj Optional instance to populate.
     * @return {module:model/GetCallbackLogsDataItems} The populated <code>GetCallbackLogsDataItems</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetCallbackLogsDataItems();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
            if (data.hasOwnProperty('msg')) {
                obj['msg'] = ApiClient.convertToType(data['msg'], 'String');
            }
            if (data.hasOwnProperty('time')) {
                obj['time'] = ApiClient.convertToType(data['time'], 'String');
            }
        }
        return obj;
    }


}

/**
 * HTTP code for the callback
 * @member {Number} code
 */
GetCallbackLogsDataItems.prototype['code'] = undefined;

/**
 * HTTP or AWS SQS response message from the server
 * @member {String} msg
 */
GetCallbackLogsDataItems.prototype['msg'] = undefined;

/**
 * Time of callback in RFC 2822 or UNIX epoch format
 * @member {String} time
 */
GetCallbackLogsDataItems.prototype['time'] = undefined;






export default GetCallbackLogsDataItems;

