/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetCallbackDetailsData model module.
 * @module model/GetCallbackDetailsData
 * @version 4.0.0
 */
class GetCallbackDetailsData {
    /**
     * Constructs a new <code>GetCallbackDetailsData</code>.
     * data object
     * @alias module:model/GetCallbackDetailsData
     */
    constructor() { 
        
        GetCallbackDetailsData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetCallbackDetailsData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetCallbackDetailsData} obj Optional instance to populate.
     * @return {module:model/GetCallbackDetailsData} The populated <code>GetCallbackDetailsData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetCallbackDetailsData();

            if (data.hasOwnProperty('medium')) {
                obj['medium'] = ApiClient.convertToType(data['medium'], 'String');
            }
            if (data.hasOwnProperty('event')) {
                obj['event'] = ApiClient.convertToType(data['event'], 'String');
            }
            if (data.hasOwnProperty('channel')) {
                obj['channel'] = ApiClient.convertToType(data['channel'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('aws_data')) {
                obj['aws_data'] = ApiClient.convertToType(data['aws_data'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Medium by which the callback data is sent. Possible values are one of:   * http   * aws 
 * @member {module:model/GetCallbackDetailsData.MediumEnum} medium
 */
GetCallbackDetailsData.prototype['medium'] = undefined;

/**
 * Event for which the callback has been created. Valid types are:  * delivered -  message delivered * failed - message bounced * complained - complaint received * bounceback - bounce back notification received * received - message received by our system * queued - message in queue (transient) * hard_bounced - hard bounce received * opened - message opened * clicked - URL in message clicked * unsubscribed - unsubscribe received 
 * @member {String} event
 */
GetCallbackDetailsData.prototype['event'] = undefined;

/**
 * Name of the channel for which the callback has been created
 * @member {String} channel
 */
GetCallbackDetailsData.prototype['channel'] = undefined;

/**
 * Address to which the callback data is sent. This will be either a URL for http-based callbacks or the Amazon SQS queue name for SQS-based callbacks
 * @member {String} address
 */
GetCallbackDetailsData.prototype['address'] = undefined;

/**
 * Amazon SQS settings
 * @member {String} aws_data
 */
GetCallbackDetailsData.prototype['aws_data'] = undefined;





/**
 * Allowed values for the <code>medium</code> property.
 * @enum {String}
 * @readonly
 */
GetCallbackDetailsData['MediumEnum'] = {

    /**
     * value: "http"
     * @const
     */
    "http": "http",

    /**
     * value: "aws"
     * @const
     */
    "aws": "aws"
};



export default GetCallbackDetailsData;

