/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetCallbackLogsDataItems from './GetCallbackLogsDataItems';

/**
 * The GetCallbackLogsData model module.
 * @module model/GetCallbackLogsData
 * @version 4.0.0
 */
class GetCallbackLogsData {
    /**
     * Constructs a new <code>GetCallbackLogsData</code>.
     * Callback Logs
     * @alias module:model/GetCallbackLogsData
     */
    constructor() { 
        
        GetCallbackLogsData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetCallbackLogsData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetCallbackLogsData} obj Optional instance to populate.
     * @return {module:model/GetCallbackLogsData} The populated <code>GetCallbackLogsData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetCallbackLogsData();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [GetCallbackLogsDataItems]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/GetCallbackLogsDataItems>} items
 */
GetCallbackLogsData.prototype['items'] = undefined;






export default GetCallbackLogsData;

