/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetDomainsResponseDataItems model module.
 * @module model/GetDomainsResponseDataItems
 * @version 4.0.0
 */
class GetDomainsResponseDataItems {
    /**
     * Constructs a new <code>GetDomainsResponseDataItems</code>.
     * @alias module:model/GetDomainsResponseDataItems
     */
    constructor() { 
        
        GetDomainsResponseDataItems.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetDomainsResponseDataItems</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetDomainsResponseDataItems} obj Optional instance to populate.
     * @return {module:model/GetDomainsResponseDataItems} The populated <code>GetDomainsResponseDataItems</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetDomainsResponseDataItems();

            if (data.hasOwnProperty('domain_name')) {
                obj['domain_name'] = ApiClient.convertToType(data['domain_name'], 'String');
            }
            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Registered domain name
 * @member {String} domain_name
 */
GetDomainsResponseDataItems.prototype['domain_name'] = undefined;

/**
 * Flag indicating whether the domain is enabled for the given account
 * @member {Boolean} enabled
 */
GetDomainsResponseDataItems.prototype['enabled'] = undefined;






export default GetDomainsResponseDataItems;

