/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GetDomainDetailsData model module.
 * @module model/GetDomainDetailsData
 * @version 4.0.0
 */
class GetDomainDetailsData {
    /**
     * Constructs a new <code>GetDomainDetailsData</code>.
     * Domains
     * @alias module:model/GetDomainDetailsData
     */
    constructor() { 
        
        GetDomainDetailsData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetDomainDetailsData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetDomainDetailsData} obj Optional instance to populate.
     * @return {module:model/GetDomainDetailsData} The populated <code>GetDomainDetailsData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetDomainDetailsData();

            if (data.hasOwnProperty('domain_name')) {
                obj['domain_name'] = ApiClient.convertToType(data['domain_name'], 'String');
            }
            if (data.hasOwnProperty('selector')) {
                obj['selector'] = ApiClient.convertToType(data['selector'], 'String');
            }
            if (data.hasOwnProperty('private_key')) {
                obj['private_key'] = ApiClient.convertToType(data['private_key'], 'String');
            }
            if (data.hasOwnProperty('is_valid')) {
                obj['is_valid'] = ApiClient.convertToType(data['is_valid'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Registered domain name
 * @member {String} domain_name
 */
GetDomainDetailsData.prototype['domain_name'] = undefined;

/**
 * Name of the DKIM selector for this domain
 * @member {String} selector
 */
GetDomainDetailsData.prototype['selector'] = undefined;

/**
 * Private key of the DKIM record
 * @member {String} private_key
 */
GetDomainDetailsData.prototype['private_key'] = undefined;

/**
 * Boolean flag indicating whether this DKIM is valid – i.e. private key matches the public key, identified by a selector for this domain
 * @member {Boolean} is_valid
 */
GetDomainDetailsData.prototype['is_valid'] = undefined;






export default GetDomainDetailsData;

