/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V4MessagesBody from './V4MessagesBody';
import V4MessagesOriginator from './V4MessagesOriginator';
import V4MessagesRecipients from './V4MessagesRecipients';

/**
 * The InlineObject model module.
 * @module model/InlineObject
 * @version 4.0.0
 */
class InlineObject {
    /**
     * Constructs a new <code>InlineObject</code>.
     * @alias module:model/InlineObject
     */
    constructor() { 
        
        InlineObject.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineObject</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject} obj Optional instance to populate.
     * @return {module:model/InlineObject} The populated <code>InlineObject</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject();

            if (data.hasOwnProperty('channel')) {
                obj['channel'] = ApiClient.convertToType(data['channel'], 'String');
            }
            if (data.hasOwnProperty('recipients')) {
                obj['recipients'] = V4MessagesRecipients.constructFromObject(data['recipients']);
            }
            if (data.hasOwnProperty('originator')) {
                obj['originator'] = V4MessagesOriginator.constructFromObject(data['originator']);
            }
            if (data.hasOwnProperty('custom_headers')) {
                obj['custom_headers'] = ApiClient.convertToType(data['custom_headers'], Object);
            }
            if (data.hasOwnProperty('subject')) {
                obj['subject'] = ApiClient.convertToType(data['subject'], 'String');
            }
            if (data.hasOwnProperty('body')) {
                obj['body'] = V4MessagesBody.constructFromObject(data['body']);
            }
        }
        return obj;
    }


}

/**
 * Name of  the channel through which the email will be sent
 * @member {String} channel
 */
InlineObject.prototype['channel'] = undefined;

/**
 * @member {module:model/V4MessagesRecipients} recipients
 */
InlineObject.prototype['recipients'] = undefined;

/**
 * @member {module:model/V4MessagesOriginator} originator
 */
InlineObject.prototype['originator'] = undefined;

/**
 * A name of a header to customize (both standard and non-standard) and its value, which can be either string or array of strings
 * @member {Object} custom_headers
 */
InlineObject.prototype['custom_headers'] = undefined;

/**
 * Email subject. Multiline value is supported, `998` characters max
 * @member {String} subject
 */
InlineObject.prototype['subject'] = undefined;

/**
 * @member {module:model/V4MessagesBody} body
 */
InlineObject.prototype['body'] = undefined;






export default InlineObject;

