/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V4MessagesMimeRecipients from './V4MessagesMimeRecipients';
import V4MessagesOriginator from './V4MessagesOriginator';

/**
 * The InlineObject1 model module.
 * @module model/InlineObject1
 * @version 4.0.0
 */
class InlineObject1 {
    /**
     * Constructs a new <code>InlineObject1</code>.
     * @alias module:model/InlineObject1
     */
    constructor() { 
        
        InlineObject1.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineObject1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject1} obj Optional instance to populate.
     * @return {module:model/InlineObject1} The populated <code>InlineObject1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject1();

            if (data.hasOwnProperty('mime')) {
                obj['mime'] = ApiClient.convertToType(data['mime'], 'String');
            }
            if (data.hasOwnProperty('channel')) {
                obj['channel'] = ApiClient.convertToType(data['channel'], 'String');
            }
            if (data.hasOwnProperty('recipients')) {
                obj['recipients'] = V4MessagesMimeRecipients.constructFromObject(data['recipients']);
            }
            if (data.hasOwnProperty('originator')) {
                obj['originator'] = V4MessagesOriginator.constructFromObject(data['originator']);
            }
        }
        return obj;
    }


}

/**
 * A completely prepared full MIME container of the email, compliant with RFC 2045, RFC 2046, RFC 2047, RFC 4288, RFC 4289 and RFC 2049. No validation will be performed during API submission and it will be attempted to be delivered as is. Any errors while processing and delivering this email will be available only via callbacks.  
 * @member {String} mime
 */
InlineObject1.prototype['mime'] = undefined;

/**
 * Name of the channel through which the email will be sent.
 * @member {String} channel
 */
InlineObject1.prototype['channel'] = undefined;

/**
 * @member {module:model/V4MessagesMimeRecipients} recipients
 */
InlineObject1.prototype['recipients'] = undefined;

/**
 * @member {module:model/V4MessagesOriginator} originator
 */
InlineObject1.prototype['originator'] = undefined;






export default InlineObject1;

