/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InvalidKeyDataErrors model module.
 * @module model/InvalidKeyDataErrors
 * @version 4.0.0
 */
class InvalidKeyDataErrors {
    /**
     * Constructs a new <code>InvalidKeyDataErrors</code>.
     * error object
     * @alias module:model/InvalidKeyDataErrors
     */
    constructor() { 
        
        InvalidKeyDataErrors.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InvalidKeyDataErrors</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InvalidKeyDataErrors} obj Optional instance to populate.
     * @return {module:model/InvalidKeyDataErrors} The populated <code>InvalidKeyDataErrors</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InvalidKeyDataErrors();

            if (data.hasOwnProperty('error_field')) {
                obj['error_field'] = ApiClient.convertToType(data['error_field'], 'String');
            }
        }
        return obj;
    }


}

/**
 * error message
 * @member {String} error_field
 */
InvalidKeyDataErrors.prototype['error_field'] = undefined;






export default InvalidKeyDataErrors;

