/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MessagesResponseDataAbuse from './MessagesResponseDataAbuse';
import MessagesResponseDataClicks from './MessagesResponseDataClicks';
import MessagesResponseDataDetails from './MessagesResponseDataDetails';
import MessagesResponseDataMsgData from './MessagesResponseDataMsgData';
import MessagesResponseDataOpens from './MessagesResponseDataOpens';
import MessagesResponseDataUnsubs from './MessagesResponseDataUnsubs';

/**
 * The MessagesResponseDataItems model module.
 * @module model/MessagesResponseDataItems
 * @version 4.0.0
 */
class MessagesResponseDataItems {
    /**
     * Constructs a new <code>MessagesResponseDataItems</code>.
     * @alias module:model/MessagesResponseDataItems
     */
    constructor() { 
        
        MessagesResponseDataItems.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MessagesResponseDataItems</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MessagesResponseDataItems} obj Optional instance to populate.
     * @return {module:model/MessagesResponseDataItems} The populated <code>MessagesResponseDataItems</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessagesResponseDataItems();

            if (data.hasOwnProperty('msg_id')) {
                obj['msg_id'] = ApiClient.convertToType(data['msg_id'], 'String');
            }
            if (data.hasOwnProperty('msg_time')) {
                obj['msg_time'] = ApiClient.convertToType(data['msg_time'], 'Number');
            }
            if (data.hasOwnProperty('channel')) {
                obj['channel'] = ApiClient.convertToType(data['channel'], 'String');
            }
            if (data.hasOwnProperty('smtp_vars')) {
                obj['smtp_vars'] = ApiClient.convertToType(data['smtp_vars'], Object);
            }
            if (data.hasOwnProperty('msg_data')) {
                obj['msg_data'] = MessagesResponseDataMsgData.constructFromObject(data['msg_data']);
            }
            if (data.hasOwnProperty('details')) {
                obj['details'] = MessagesResponseDataDetails.constructFromObject(data['details']);
            }
            if (data.hasOwnProperty('opens')) {
                obj['opens'] = MessagesResponseDataOpens.constructFromObject(data['opens']);
            }
            if (data.hasOwnProperty('clicks')) {
                obj['clicks'] = MessagesResponseDataClicks.constructFromObject(data['clicks']);
            }
            if (data.hasOwnProperty('abuse')) {
                obj['abuse'] = MessagesResponseDataAbuse.constructFromObject(data['abuse']);
            }
            if (data.hasOwnProperty('unsubs')) {
                obj['unsubs'] = MessagesResponseDataUnsubs.constructFromObject(data['unsubs']);
            }
        }
        return obj;
    }


}

/**
 * Unique message ID
 * @member {String} msg_id
 */
MessagesResponseDataItems.prototype['msg_id'] = undefined;

/**
 * Time at which the message was sent
 * @member {Number} msg_time
 */
MessagesResponseDataItems.prototype['msg_time'] = undefined;

/**
 * Name of the channel on which the message was sent
 * @member {String} channel
 */
MessagesResponseDataItems.prototype['channel'] = undefined;

/**
 * Custom parameters and their value echoed back from `X-SMTPAPI` header's `unique_args` parameter
 * @member {Object} smtp_vars
 */
MessagesResponseDataItems.prototype['smtp_vars'] = undefined;

/**
 * @member {module:model/MessagesResponseDataMsgData} msg_data
 */
MessagesResponseDataItems.prototype['msg_data'] = undefined;

/**
 * @member {module:model/MessagesResponseDataDetails} details
 */
MessagesResponseDataItems.prototype['details'] = undefined;

/**
 * @member {module:model/MessagesResponseDataOpens} opens
 */
MessagesResponseDataItems.prototype['opens'] = undefined;

/**
 * @member {module:model/MessagesResponseDataClicks} clicks
 */
MessagesResponseDataItems.prototype['clicks'] = undefined;

/**
 * @member {module:model/MessagesResponseDataAbuse} abuse
 */
MessagesResponseDataItems.prototype['abuse'] = undefined;

/**
 * @member {module:model/MessagesResponseDataUnsubs} unsubs
 */
MessagesResponseDataItems.prototype['unsubs'] = undefined;






export default MessagesResponseDataItems;

