/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MessagesResponseDataClicksItems from './MessagesResponseDataClicksItems';

/**
 * The MessagesResponseDataClicks model module.
 * @module model/MessagesResponseDataClicks
 * @version 4.0.0
 */
class MessagesResponseDataClicks {
    /**
     * Constructs a new <code>MessagesResponseDataClicks</code>.
     * Clicks Data
     * @alias module:model/MessagesResponseDataClicks
     */
    constructor() { 
        
        MessagesResponseDataClicks.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MessagesResponseDataClicks</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MessagesResponseDataClicks} obj Optional instance to populate.
     * @return {module:model/MessagesResponseDataClicks} The populated <code>MessagesResponseDataClicks</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessagesResponseDataClicks();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [MessagesResponseDataClicksItems]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/MessagesResponseDataClicksItems>} items
 */
MessagesResponseDataClicks.prototype['items'] = undefined;






export default MessagesResponseDataClicks;

