/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MessagesResponseDataDetailsDelivery model module.
 * @module model/MessagesResponseDataDetailsDelivery
 * @version 4.0.0
 */
class MessagesResponseDataDetailsDelivery {
    /**
     * Constructs a new <code>MessagesResponseDataDetailsDelivery</code>.
     * @alias module:model/MessagesResponseDataDetailsDelivery
     */
    constructor() { 
        
        MessagesResponseDataDetailsDelivery.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MessagesResponseDataDetailsDelivery</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MessagesResponseDataDetailsDelivery} obj Optional instance to populate.
     * @return {module:model/MessagesResponseDataDetailsDelivery} The populated <code>MessagesResponseDataDetailsDelivery</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessagesResponseDataDetailsDelivery();

            if (data.hasOwnProperty('finished')) {
                obj['finished'] = ApiClient.convertToType(data['finished'], 'String');
            }
            if (data.hasOwnProperty('retries')) {
                obj['retries'] = ApiClient.convertToType(data['retries'], 'Number');
            }
            if (data.hasOwnProperty('event')) {
                obj['event'] = ApiClient.convertToType(data['event'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Timestamp of when the message was delivered
 * @member {String} finished
 */
MessagesResponseDataDetailsDelivery.prototype['finished'] = undefined;

/**
 * Number of retries after the initial delivery attempt
 * @member {Number} retries
 */
MessagesResponseDataDetailsDelivery.prototype['retries'] = undefined;

/**
 * One of:    * delivered   * failed   * queued 
 * @member {String} event
 */
MessagesResponseDataDetailsDelivery.prototype['event'] = undefined;

/**
 * The last SMTP response code received from a peer
 * @member {String} code
 */
MessagesResponseDataDetailsDelivery.prototype['code'] = undefined;

/**
 * The last SMTP response message received from a peer
 * @member {String} status
 */
MessagesResponseDataDetailsDelivery.prototype['status'] = undefined;






export default MessagesResponseDataDetailsDelivery;

