/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MessagesResponseDataMsgData model module.
 * @module model/MessagesResponseDataMsgData
 * @version 4.0.0
 */
class MessagesResponseDataMsgData {
    /**
     * Constructs a new <code>MessagesResponseDataMsgData</code>.
     * @alias module:model/MessagesResponseDataMsgData
     */
    constructor() { 
        
        MessagesResponseDataMsgData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MessagesResponseDataMsgData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MessagesResponseDataMsgData} obj Optional instance to populate.
     * @return {module:model/MessagesResponseDataMsgData} The populated <code>MessagesResponseDataMsgData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessagesResponseDataMsgData();

            if (data.hasOwnProperty('rcpt_to')) {
                obj['rcpt_to'] = ApiClient.convertToType(data['rcpt_to'], 'String');
            }
            if (data.hasOwnProperty('from')) {
                obj['from'] = ApiClient.convertToType(data['from'], 'String');
            }
            if (data.hasOwnProperty('subject')) {
                obj['subject'] = ApiClient.convertToType(data['subject'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Email address of the recipient
 * @member {String} rcpt_to
 */
MessagesResponseDataMsgData.prototype['rcpt_to'] = undefined;

/**
 * Email address of the sender
 * @member {String} from
 */
MessagesResponseDataMsgData.prototype['from'] = undefined;

/**
 * Message subject
 * @member {String} subject
 */
MessagesResponseDataMsgData.prototype['subject'] = undefined;






export default MessagesResponseDataMsgData;

