/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MessagesResponseDataAbuseComplaints from './MessagesResponseDataAbuseComplaints';

/**
 * The MessagesResponseDataAbuse model module.
 * @module model/MessagesResponseDataAbuse
 * @version 4.0.0
 */
class MessagesResponseDataAbuse {
    /**
     * Constructs a new <code>MessagesResponseDataAbuse</code>.
     * Abuse Data
     * @alias module:model/MessagesResponseDataAbuse
     */
    constructor() { 
        
        MessagesResponseDataAbuse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MessagesResponseDataAbuse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MessagesResponseDataAbuse} obj Optional instance to populate.
     * @return {module:model/MessagesResponseDataAbuse} The populated <code>MessagesResponseDataAbuse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessagesResponseDataAbuse();

            if (data.hasOwnProperty('complaints')) {
                obj['complaints'] = ApiClient.convertToType(data['complaints'], [MessagesResponseDataAbuseComplaints]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/MessagesResponseDataAbuseComplaints>} complaints
 */
MessagesResponseDataAbuse.prototype['complaints'] = undefined;






export default MessagesResponseDataAbuse;

