/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MessagesResponseDataClicksItems model module.
 * @module model/MessagesResponseDataClicksItems
 * @version 4.0.0
 */
class MessagesResponseDataClicksItems {
    /**
     * Constructs a new <code>MessagesResponseDataClicksItems</code>.
     * @alias module:model/MessagesResponseDataClicksItems
     */
    constructor() { 
        
        MessagesResponseDataClicksItems.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MessagesResponseDataClicksItems</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MessagesResponseDataClicksItems} obj Optional instance to populate.
     * @return {module:model/MessagesResponseDataClicksItems} The populated <code>MessagesResponseDataClicksItems</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessagesResponseDataClicksItems();

            if (data.hasOwnProperty('click_time')) {
                obj['click_time'] = ApiClient.convertToType(data['click_time'], 'String');
            }
            if (data.hasOwnProperty('remote_ip')) {
                obj['remote_ip'] = ApiClient.convertToType(data['remote_ip'], 'String');
            }
            if (data.hasOwnProperty('ua')) {
                obj['ua'] = ApiClient.convertToType(data['ua'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Timestamp of when message links were clicked
 * @member {String} click_time
 */
MessagesResponseDataClicksItems.prototype['click_time'] = undefined;

/**
 * IP address of where links were clicked
 * @member {String} remote_ip
 */
MessagesResponseDataClicksItems.prototype['remote_ip'] = undefined;

/**
 * User agent of device on which links were clicked
 * @member {String} ua
 */
MessagesResponseDataClicksItems.prototype['ua'] = undefined;






export default MessagesResponseDataClicksItems;

