/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MessagesResponseDataAbuseComplaints model module.
 * @module model/MessagesResponseDataAbuseComplaints
 * @version 4.0.0
 */
class MessagesResponseDataAbuseComplaints {
    /**
     * Constructs a new <code>MessagesResponseDataAbuseComplaints</code>.
     * @alias module:model/MessagesResponseDataAbuseComplaints
     */
    constructor() { 
        
        MessagesResponseDataAbuseComplaints.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MessagesResponseDataAbuseComplaints</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MessagesResponseDataAbuseComplaints} obj Optional instance to populate.
     * @return {module:model/MessagesResponseDataAbuseComplaints} The populated <code>MessagesResponseDataAbuseComplaints</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessagesResponseDataAbuseComplaints();

            if (data.hasOwnProperty('report_time')) {
                obj['report_time'] = ApiClient.convertToType(data['report_time'], 'String');
            }
            if (data.hasOwnProperty('provider')) {
                obj['provider'] = ApiClient.convertToType(data['provider'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Time when the complaint was made
 * @member {String} report_time
 */
MessagesResponseDataAbuseComplaints.prototype['report_time'] = undefined;

/**
 * Abuse provider information
 * @member {String} provider
 */
MessagesResponseDataAbuseComplaints.prototype['provider'] = undefined;






export default MessagesResponseDataAbuseComplaints;

