/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MessagesResponseDataOpensItems model module.
 * @module model/MessagesResponseDataOpensItems
 * @version 4.0.0
 */
class MessagesResponseDataOpensItems {
    /**
     * Constructs a new <code>MessagesResponseDataOpensItems</code>.
     * @alias module:model/MessagesResponseDataOpensItems
     */
    constructor() { 
        
        MessagesResponseDataOpensItems.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MessagesResponseDataOpensItems</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MessagesResponseDataOpensItems} obj Optional instance to populate.
     * @return {module:model/MessagesResponseDataOpensItems} The populated <code>MessagesResponseDataOpensItems</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessagesResponseDataOpensItems();

            if (data.hasOwnProperty('open_time')) {
                obj['open_time'] = ApiClient.convertToType(data['open_time'], 'String');
            }
            if (data.hasOwnProperty('remote_ip')) {
                obj['remote_ip'] = ApiClient.convertToType(data['remote_ip'], 'String');
            }
            if (data.hasOwnProperty('ua')) {
                obj['ua'] = ApiClient.convertToType(data['ua'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Timestamp of when the message was opened
 * @member {String} open_time
 */
MessagesResponseDataOpensItems.prototype['open_time'] = undefined;

/**
 * IP address of where the message was opened
 * @member {String} remote_ip
 */
MessagesResponseDataOpensItems.prototype['remote_ip'] = undefined;

/**
 * User agent of device on which the message was opened
 * @member {String} ua
 */
MessagesResponseDataOpensItems.prototype['ua'] = undefined;






export default MessagesResponseDataOpensItems;

