/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MessagesResponseDataUnsubsItems model module.
 * @module model/MessagesResponseDataUnsubsItems
 * @version 4.0.0
 */
class MessagesResponseDataUnsubsItems {
    /**
     * Constructs a new <code>MessagesResponseDataUnsubsItems</code>.
     * @alias module:model/MessagesResponseDataUnsubsItems
     */
    constructor() { 
        
        MessagesResponseDataUnsubsItems.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MessagesResponseDataUnsubsItems</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MessagesResponseDataUnsubsItems} obj Optional instance to populate.
     * @return {module:model/MessagesResponseDataUnsubsItems} The populated <code>MessagesResponseDataUnsubsItems</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessagesResponseDataUnsubsItems();

            if (data.hasOwnProperty('unsub_time')) {
                obj['unsub_time'] = ApiClient.convertToType(data['unsub_time'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Time when the unsubscribe request was made
 * @member {String} unsub_time
 */
MessagesResponseDataUnsubsItems.prototype['unsub_time'] = undefined;






export default MessagesResponseDataUnsubsItems;

