/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostMessageResponseData model module.
 * @module model/PostMessageResponseData
 * @version 4.0.0
 */
class PostMessageResponseData {
    /**
     * Constructs a new <code>PostMessageResponseData</code>.
     * @alias module:model/PostMessageResponseData
     */
    constructor() { 
        
        PostMessageResponseData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PostMessageResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostMessageResponseData} obj Optional instance to populate.
     * @return {module:model/PostMessageResponseData} The populated <code>PostMessageResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostMessageResponseData();

            if (data.hasOwnProperty('msg_id')) {
                obj['msg_id'] = ApiClient.convertToType(data['msg_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Unique Message ID of accepted message
 * @member {String} msg_id
 */
PostMessageResponseData.prototype['msg_id'] = undefined;






export default PostMessageResponseData;

