/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ReportsDataOndemand from './ReportsDataOndemand';
import ReportsDataPeriodic from './ReportsDataPeriodic';

/**
 * The ReportsData model module.
 * @module model/ReportsData
 * @version 4.0.0
 */
class ReportsData {
    /**
     * Constructs a new <code>ReportsData</code>.
     * Periodic Reports
     * @alias module:model/ReportsData
     */
    constructor() { 
        
        ReportsData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReportsData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReportsData} obj Optional instance to populate.
     * @return {module:model/ReportsData} The populated <code>ReportsData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReportsData();

            if (data.hasOwnProperty('periodic')) {
                obj['periodic'] = ApiClient.convertToType(data['periodic'], [ReportsDataPeriodic]);
            }
            if (data.hasOwnProperty('ondemand')) {
                obj['ondemand'] = ApiClient.convertToType(data['ondemand'], [ReportsDataOndemand]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/ReportsDataPeriodic>} periodic
 */
ReportsData.prototype['periodic'] = undefined;

/**
 * @member {Array.<module:model/ReportsDataOndemand>} ondemand
 */
ReportsData.prototype['ondemand'] = undefined;






export default ReportsData;

