/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ReportsDataPeriodic model module.
 * @module model/ReportsDataPeriodic
 * @version 4.0.0
 */
class ReportsDataPeriodic {
    /**
     * Constructs a new <code>ReportsDataPeriodic</code>.
     * @alias module:model/ReportsDataPeriodic
     */
    constructor() { 
        
        ReportsDataPeriodic.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReportsDataPeriodic</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReportsDataPeriodic} obj Optional instance to populate.
     * @return {module:model/ReportsDataPeriodic} The populated <code>ReportsDataPeriodic</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReportsDataPeriodic();

            if (data.hasOwnProperty('frequency')) {
                obj['frequency'] = ApiClient.convertToType(data['frequency'], 'String');
            }
            if (data.hasOwnProperty('report_id')) {
                obj['report_id'] = ApiClient.convertToType(data['report_id'], 'String');
            }
            if (data.hasOwnProperty('events')) {
                obj['events'] = ApiClient.convertToType(data['events'], 'String');
            }
            if (data.hasOwnProperty('channel')) {
                obj['channel'] = ApiClient.convertToType(data['channel'], 'String');
            }
            if (data.hasOwnProperty('report_time')) {
                obj['report_time'] = ApiClient.convertToType(data['report_time'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Periodic report frequency
 * @member {module:model/ReportsDataPeriodic.FrequencyEnum} frequency
 */
ReportsDataPeriodic.prototype['frequency'] = undefined;

/**
 * Unique report ID
 * @member {String} report_id
 */
ReportsDataPeriodic.prototype['report_id'] = undefined;

/**
 * Preset of events returned in a periodic report
 * @member {String} events
 */
ReportsDataPeriodic.prototype['events'] = undefined;

/**
 * Name of the channel for which a given report has been defined
 * @member {String} channel
 */
ReportsDataPeriodic.prototype['channel'] = undefined;

/**
 * The hour at which the report should be sent, values range from 0 to 23
 * @member {String} report_time
 */
ReportsDataPeriodic.prototype['report_time'] = undefined;





/**
 * Allowed values for the <code>frequency</code> property.
 * @enum {String}
 * @readonly
 */
ReportsDataPeriodic['FrequencyEnum'] = {

    /**
     * value: "monthly"
     * @const
     */
    "monthly": "monthly",

    /**
     * value: "weekly"
     * @const
     */
    "weekly": "weekly",

    /**
     * value: "daily"
     * @const
     */
    "daily": "daily"
};



export default ReportsDataPeriodic;

