/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ReportsDataOndemand model module.
 * @module model/ReportsDataOndemand
 * @version 4.0.0
 */
class ReportsDataOndemand {
    /**
     * Constructs a new <code>ReportsDataOndemand</code>.
     * @alias module:model/ReportsDataOndemand
     */
    constructor() { 
        
        ReportsDataOndemand.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ReportsDataOndemand</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReportsDataOndemand} obj Optional instance to populate.
     * @return {module:model/ReportsDataOndemand} The populated <code>ReportsDataOndemand</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReportsDataOndemand();

            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('time_req')) {
                obj['time_req'] = ApiClient.convertToType(data['time_req'], 'Number');
            }
            if (data.hasOwnProperty('progress')) {
                obj['progress'] = ApiClient.convertToType(data['progress'], 'Number');
            }
            if (data.hasOwnProperty('channel')) {
                obj['channel'] = ApiClient.convertToType(data['channel'], 'String');
            }
            if (data.hasOwnProperty('report_id')) {
                obj['report_id'] = ApiClient.convertToType(data['report_id'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Current status of a given on-demand report
 * @member {module:model/ReportsDataOndemand.StatusEnum} status
 */
ReportsDataOndemand.prototype['status'] = undefined;

/**
 * Human readable name of an on-demand report (auto-generated)
 * @member {String} name
 */
ReportsDataOndemand.prototype['name'] = undefined;

/**
 * The unique URL from which to download an on-demand report
 * @member {String} url
 */
ReportsDataOndemand.prototype['url'] = undefined;

/**
 * Time when a given on-demand report has been requestedi. RFC 2822 or UNIX epoch format
 * @member {Number} time_req
 */
ReportsDataOndemand.prototype['time_req'] = undefined;

/**
 * Percentage of completion for an on-demand report
 * @member {Number} progress
 */
ReportsDataOndemand.prototype['progress'] = undefined;

/**
 * Name of the channel for which a given report has been defined
 * @member {String} channel
 */
ReportsDataOndemand.prototype['channel'] = undefined;

/**
 * Unique report ID
 * @member {String} report_id
 */
ReportsDataOndemand.prototype['report_id'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
ReportsDataOndemand['StatusEnum'] = {

    /**
     * value: "in_progress"
     * @const
     */
    "in_progress": "in_progress",

    /**
     * value: "done"
     * @const
     */
    "done": "done",

    /**
     * value: "pending"
     * @const
     */
    "pending": "pending"
};



export default ReportsDataOndemand;

