/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Report model module.
 * @module model/Report
 * @version 4.0.0
 */
class Report {
    /**
     * Constructs a new <code>Report</code>.
     * @alias module:model/Report
     */
    constructor() { 
        
        Report.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Report</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Report} obj Optional instance to populate.
     * @return {module:model/Report} The populated <code>Report</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Report();

            if (data.hasOwnProperty('frequency')) {
                obj['frequency'] = ApiClient.convertToType(data['frequency'], 'String');
            }
            if (data.hasOwnProperty('report_id')) {
                obj['report_id'] = ApiClient.convertToType(data['report_id'], 'String');
            }
            if (data.hasOwnProperty('events')) {
                obj['events'] = ApiClient.convertToType(data['events'], 'String');
            }
            if (data.hasOwnProperty('channel')) {
                obj['channel'] = ApiClient.convertToType(data['channel'], 'String');
            }
            if (data.hasOwnProperty('report_time')) {
                obj['report_time'] = ApiClient.convertToType(data['report_time'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('time_req')) {
                obj['time_req'] = ApiClient.convertToType(data['time_req'], 'Number');
            }
            if (data.hasOwnProperty('progress')) {
                obj['progress'] = ApiClient.convertToType(data['progress'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Report frequency – one of:   * daily - every day at a specified hour   * weekly - Mondays at a specified hour   * monthly - 1st day of the month at a specified hour 
 * @member {module:model/Report.FrequencyEnum} frequency
 */
Report.prototype['frequency'] = undefined;

/**
 * Unique report ID
 * @member {String} report_id
 */
Report.prototype['report_id'] = undefined;

/**
 * Preset of events returned in a report:    * hard_bounced   * failed   * delivered   * sent   * pending   * total   * abuse If not specified all events are included. 
 * @member {String} events
 */
Report.prototype['events'] = undefined;

/**
 * Name of channel (sender). If not specified all channels will be reported
 * @member {String} channel
 */
Report.prototype['channel'] = undefined;

/**
 * The hour at which the report should be sent, values range from 0 to 23
 * @member {String} report_time
 */
Report.prototype['report_time'] = undefined;

/**
 * Current status of a given on-demand report
 * @member {module:model/Report.StatusEnum} status
 */
Report.prototype['status'] = undefined;

/**
 * Human readable name of an on-demand report (auto-generated)
 * @member {String} name
 */
Report.prototype['name'] = undefined;

/**
 * The unique URL from which to download an on-demand report from
 * @member {String} url
 */
Report.prototype['url'] = undefined;

/**
 * Time when a given on-demand report has been requestedi. RFC 2822 or UNIX epoch format
 * @member {Number} time_req
 */
Report.prototype['time_req'] = undefined;

/**
 * Percentage of completion for an on-demand report
 * @member {Number} progress
 */
Report.prototype['progress'] = undefined;





/**
 * Allowed values for the <code>frequency</code> property.
 * @enum {String}
 * @readonly
 */
Report['FrequencyEnum'] = {

    /**
     * value: "monthly"
     * @const
     */
    "monthly": "monthly",

    /**
     * value: "weekly"
     * @const
     */
    "weekly": "weekly",

    /**
     * value: "daily"
     * @const
     */
    "daily": "daily"
};


/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
Report['StatusEnum'] = {

    /**
     * value: "in_progress"
     * @const
     */
    "in_progress": "in_progress",

    /**
     * value: "done"
     * @const
     */
    "done": "done",

    /**
     * value: "pending"
     * @const
     */
    "pending": "pending"
};



export default Report;

