/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class SliceValue.
* @enum {}
* @readonly
*/
export default class SliceValue {
    
        /**
         * value: "channel"
         * @const
         */
        "channel" = "channel";

    
        /**
         * value: "domain"
         * @const
         */
        "domain" = "domain";

    
        /**
         * value: "rcpt_domain"
         * @const
         */
        "rcpt_domain" = "rcpt_domain";

    
        /**
         * value: "rcpt_isp"
         * @const
         */
        "rcpt_isp" = "rcpt_isp";

    

    /**
    * Returns a <code>SliceValue</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/SliceValue} The enum <code>SliceValue</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

