/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The StatsResponseDataItems model module.
 * @module model/StatsResponseDataItems
 * @version 4.0.0
 */
class StatsResponseDataItems {
    /**
     * Constructs a new <code>StatsResponseDataItems</code>.
     * @alias module:model/StatsResponseDataItems
     */
    constructor() { 
        
        StatsResponseDataItems.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StatsResponseDataItems</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StatsResponseDataItems} obj Optional instance to populate.
     * @return {module:model/StatsResponseDataItems} The populated <code>StatsResponseDataItems</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StatsResponseDataItems();

            if (data.hasOwnProperty('accepted')) {
                obj['accepted'] = ApiClient.convertToType(data['accepted'], 'Number');
            }
            if (data.hasOwnProperty('complained')) {
                obj['complained'] = ApiClient.convertToType(data['complained'], 'Number');
            }
            if (data.hasOwnProperty('delivered')) {
                obj['delivered'] = ApiClient.convertToType(data['delivered'], 'Number');
            }
            if (data.hasOwnProperty('clicked')) {
                obj['clicked'] = ApiClient.convertToType(data['clicked'], 'Number');
            }
            if (data.hasOwnProperty('opened')) {
                obj['opened'] = ApiClient.convertToType(data['opened'], 'Number');
            }
            if (data.hasOwnProperty('failed')) {
                obj['failed'] = ApiClient.convertToType(data['failed'], 'Number');
            }
            if (data.hasOwnProperty('unsubscribed')) {
                obj['unsubscribed'] = ApiClient.convertToType(data['unsubscribed'], 'Number');
            }
            if (data.hasOwnProperty('queued')) {
                obj['queued'] = ApiClient.convertToType(data['queued'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} accepted
 */
StatsResponseDataItems.prototype['accepted'] = undefined;

/**
 * @member {Number} complained
 */
StatsResponseDataItems.prototype['complained'] = undefined;

/**
 * @member {Number} delivered
 */
StatsResponseDataItems.prototype['delivered'] = undefined;

/**
 * @member {Number} clicked
 */
StatsResponseDataItems.prototype['clicked'] = undefined;

/**
 * @member {Number} opened
 */
StatsResponseDataItems.prototype['opened'] = undefined;

/**
 * @member {Number} failed
 */
StatsResponseDataItems.prototype['failed'] = undefined;

/**
 * @member {Number} unsubscribed
 */
StatsResponseDataItems.prototype['unsubscribed'] = undefined;

/**
 * @member {Number} queued
 */
StatsResponseDataItems.prototype['queued'] = undefined;






export default StatsResponseDataItems;

