/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateAccountResponseData model module.
 * @module model/UpdateAccountResponseData
 * @version 4.0.0
 */
class UpdateAccountResponseData {
    /**
     * Constructs a new <code>UpdateAccountResponseData</code>.
     * Account
     * @alias module:model/UpdateAccountResponseData
     */
    constructor() { 
        
        UpdateAccountResponseData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateAccountResponseData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateAccountResponseData} obj Optional instance to populate.
     * @return {module:model/UpdateAccountResponseData} The populated <code>UpdateAccountResponseData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateAccountResponseData();

            if (data.hasOwnProperty('account')) {
                obj['account'] = ApiClient.convertToType(data['account'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Account Update Status
 * @member {String} account
 */
UpdateAccountResponseData.prototype['account'] = undefined;






export default UpdateAccountResponseData;

