/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V4MessagesRecipientsTo from './V4MessagesRecipientsTo';

/**
 * The V4MessagesMimeRecipients model module.
 * @module model/V4MessagesMimeRecipients
 * @version 4.0.0
 */
class V4MessagesMimeRecipients {
    /**
     * Constructs a new <code>V4MessagesMimeRecipients</code>.
     * @alias module:model/V4MessagesMimeRecipients
     */
    constructor() { 
        
        V4MessagesMimeRecipients.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V4MessagesMimeRecipients</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V4MessagesMimeRecipients} obj Optional instance to populate.
     * @return {module:model/V4MessagesMimeRecipients} The populated <code>V4MessagesMimeRecipients</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V4MessagesMimeRecipients();

            if (data.hasOwnProperty('to')) {
                obj['to'] = ApiClient.convertToType(data['to'], [V4MessagesRecipientsTo]);
            }
            if (data.hasOwnProperty('cc')) {
                obj['cc'] = ApiClient.convertToType(data['cc'], [V4MessagesRecipientsTo]);
            }
            if (data.hasOwnProperty('bcc')) {
                obj['bcc'] = ApiClient.convertToType(data['bcc'], [V4MessagesRecipientsTo]);
            }
            if (data.hasOwnProperty('bulk_list')) {
                obj['bulk_list'] = ApiClient.convertToType(data['bulk_list'], [V4MessagesRecipientsTo]);
            }
        }
        return obj;
    }


}

/**
 * TO recipients list
 * @member {Array.<module:model/V4MessagesRecipientsTo>} to
 */
V4MessagesMimeRecipients.prototype['to'] = undefined;

/**
 * CC recipients list
 * @member {Array.<module:model/V4MessagesRecipientsTo>} cc
 */
V4MessagesMimeRecipients.prototype['cc'] = undefined;

/**
 * BCC recipients list
 * @member {Array.<module:model/V4MessagesRecipientsTo>} bcc
 */
V4MessagesMimeRecipients.prototype['bcc'] = undefined;

/**
 * Distribution list. Instead of an individual email to multiple recipients, multiple emails to multiple recipients will be created.
 * @member {Array.<module:model/V4MessagesRecipientsTo>} bulk_list
 */
V4MessagesMimeRecipients.prototype['bulk_list'] = undefined;






export default V4MessagesMimeRecipients;

