/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V4MessagesRecipientsTo model module.
 * @module model/V4MessagesRecipientsTo
 * @version 4.0.0
 */
class V4MessagesRecipientsTo {
    /**
     * Constructs a new <code>V4MessagesRecipientsTo</code>.
     * Full Email Address object
     * @alias module:model/V4MessagesRecipientsTo
     */
    constructor() { 
        
        V4MessagesRecipientsTo.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V4MessagesRecipientsTo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V4MessagesRecipientsTo} obj Optional instance to populate.
     * @return {module:model/V4MessagesRecipientsTo} The populated <code>V4MessagesRecipientsTo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V4MessagesRecipientsTo();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Name of a person, must be a valid RFC 2822 name
 * @member {String} name
 */
V4MessagesRecipientsTo.prototype['name'] = undefined;

/**
 * Email address, as specified in RFC 2822
 * @member {String} address
 */
V4MessagesRecipientsTo.prototype['address'] = undefined;






export default V4MessagesRecipientsTo;

