/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V4MessagesRecipientsTo from './V4MessagesRecipientsTo';

/**
 * The V4MessagesOriginator model module.
 * @module model/V4MessagesOriginator
 * @version 4.0.0
 */
class V4MessagesOriginator {
    /**
     * Constructs a new <code>V4MessagesOriginator</code>.
     * At least one of &#x60;from&#x60; or &#x60;reply_to&#x60; must be specified here.
     * @alias module:model/V4MessagesOriginator
     */
    constructor() { 
        
        V4MessagesOriginator.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V4MessagesOriginator</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V4MessagesOriginator} obj Optional instance to populate.
     * @return {module:model/V4MessagesOriginator} The populated <code>V4MessagesOriginator</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V4MessagesOriginator();

            if (data.hasOwnProperty('from')) {
                obj['from'] = V4MessagesRecipientsTo.constructFromObject(data['from']);
            }
            if (data.hasOwnProperty('reply_to')) {
                obj['reply_to'] = V4MessagesRecipientsTo.constructFromObject(data['reply_to']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/V4MessagesRecipientsTo} from
 */
V4MessagesOriginator.prototype['from'] = undefined;

/**
 * @member {module:model/V4MessagesRecipientsTo} reply_to
 */
V4MessagesOriginator.prototype['reply_to'] = undefined;






export default V4MessagesOriginator;

