/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V4MessagesBodyAttachments model module.
 * @module model/V4MessagesBodyAttachments
 * @version 4.0.0
 */
class V4MessagesBodyAttachments {
    /**
     * Constructs a new <code>V4MessagesBodyAttachments</code>.
     * @alias module:model/V4MessagesBodyAttachments
     */
    constructor() { 
        
        V4MessagesBodyAttachments.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V4MessagesBodyAttachments</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V4MessagesBodyAttachments} obj Optional instance to populate.
     * @return {module:model/V4MessagesBodyAttachments} The populated <code>V4MessagesBodyAttachments</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V4MessagesBodyAttachments();

            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('disposition')) {
                obj['disposition'] = ApiClient.convertToType(data['disposition'], 'String');
            }
            if (data.hasOwnProperty('filename')) {
                obj['filename'] = ApiClient.convertToType(data['filename'], 'String');
            }
            if (data.hasOwnProperty('cid')) {
                obj['cid'] = ApiClient.convertToType(data['cid'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
        }
        return obj;
    }


}

/**
 * MIME version. By default set to `1.0`
 * @member {String} version
 */
V4MessagesBodyAttachments.prototype['version'] = undefined;

/**
 * MIME type. By default set to `application/octet-stream`
 * @member {String} type
 */
V4MessagesBodyAttachments.prototype['type'] = undefined;

/**
 * Content-disposition, either `inline` or `attachment`. By default set to `attachment`
 * @member {String} disposition
 */
V4MessagesBodyAttachments.prototype['disposition'] = undefined;

/**
 * Name of attached file
 * @member {String} filename
 */
V4MessagesBodyAttachments.prototype['filename'] = undefined;

/**
 * Content ID for inline dispositions. By default this is equal to the filename. Can be used in HTML content to address an attached image using “cid:” URL scheme.
 * @member {String} cid
 */
V4MessagesBodyAttachments.prototype['cid'] = undefined;

/**
 * Actual attachment content in its raw form
 * @member {String} content
 */
V4MessagesBodyAttachments.prototype['content'] = undefined;






export default V4MessagesBodyAttachments;

