/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V4MessagesBodyAttachments from './V4MessagesBodyAttachments';
import V4MessagesBodyParts from './V4MessagesBodyParts';

/**
 * The V4MessagesBody model module.
 * @module model/V4MessagesBody
 * @version 4.0.0
 */
class V4MessagesBody {
    /**
     * Constructs a new <code>V4MessagesBody</code>.
     * Array of content parts as defined below
     * @alias module:model/V4MessagesBody
     */
    constructor() { 
        
        V4MessagesBody.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V4MessagesBody</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V4MessagesBody} obj Optional instance to populate.
     * @return {module:model/V4MessagesBody} The populated <code>V4MessagesBody</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V4MessagesBody();

            if (data.hasOwnProperty('parts')) {
                obj['parts'] = ApiClient.convertToType(data['parts'], [V4MessagesBodyParts]);
            }
            if (data.hasOwnProperty('attachments')) {
                obj['attachments'] = ApiClient.convertToType(data['attachments'], [V4MessagesBodyAttachments]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/V4MessagesBodyParts>} parts
 */
V4MessagesBody.prototype['parts'] = undefined;

/**
 * @member {Array.<module:model/V4MessagesBodyAttachments>} attachments
 */
V4MessagesBody.prototype['attachments'] = undefined;






export default V4MessagesBody;

