/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import V4MessagesRecipientsTo from './V4MessagesRecipientsTo';

/**
 * The V4MessagesRecipients model module.
 * @module model/V4MessagesRecipients
 * @version 4.0.0
 */
class V4MessagesRecipients {
    /**
     * Constructs a new <code>V4MessagesRecipients</code>.
     * At least one of &#x60;to&#x60;, &#x60;cc&#x60;, &#x60;bcc&#x60; or &#x60;bulk_list&#x60; must be specified here. &#x60;bulk_list&#x60; can not be used with &#x60;to&#x60;, &#x60;cc&#x60; or &#x60;bcc&#x60; 
     * @alias module:model/V4MessagesRecipients
     */
    constructor() { 
        
        V4MessagesRecipients.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V4MessagesRecipients</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V4MessagesRecipients} obj Optional instance to populate.
     * @return {module:model/V4MessagesRecipients} The populated <code>V4MessagesRecipients</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V4MessagesRecipients();

            if (data.hasOwnProperty('to')) {
                obj['to'] = ApiClient.convertToType(data['to'], [V4MessagesRecipientsTo]);
            }
            if (data.hasOwnProperty('cc')) {
                obj['cc'] = ApiClient.convertToType(data['cc'], [V4MessagesRecipientsTo]);
            }
            if (data.hasOwnProperty('bcc')) {
                obj['bcc'] = ApiClient.convertToType(data['bcc'], [V4MessagesRecipientsTo]);
            }
            if (data.hasOwnProperty('bulk_list')) {
                obj['bulk_list'] = ApiClient.convertToType(data['bulk_list'], [V4MessagesRecipientsTo]);
            }
        }
        return obj;
    }


}

/**
 * TO recipients list
 * @member {Array.<module:model/V4MessagesRecipientsTo>} to
 */
V4MessagesRecipients.prototype['to'] = undefined;

/**
 * CC recipients list
 * @member {Array.<module:model/V4MessagesRecipientsTo>} cc
 */
V4MessagesRecipients.prototype['cc'] = undefined;

/**
 * BCC recipients list
 * @member {Array.<module:model/V4MessagesRecipientsTo>} bcc
 */
V4MessagesRecipients.prototype['bcc'] = undefined;

/**
 * Distribution list. Instead of an individual email to multiple recipients, multiple emails to multiple recipients will be created.
 * @member {Array.<module:model/V4MessagesRecipientsTo>} bulk_list
 */
V4MessagesRecipients.prototype['bulk_list'] = undefined;






export default V4MessagesRecipients;

