/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The V4MessagesBodyParts model module.
 * @module model/V4MessagesBodyParts
 * @version 4.0.0
 */
class V4MessagesBodyParts {
    /**
     * Constructs a new <code>V4MessagesBodyParts</code>.
     * @alias module:model/V4MessagesBodyParts
     */
    constructor() { 
        
        V4MessagesBodyParts.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>V4MessagesBodyParts</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/V4MessagesBodyParts} obj Optional instance to populate.
     * @return {module:model/V4MessagesBodyParts} The populated <code>V4MessagesBodyParts</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new V4MessagesBodyParts();

            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('charset')) {
                obj['charset'] = ApiClient.convertToType(data['charset'], 'String');
            }
            if (data.hasOwnProperty('encoding')) {
                obj['encoding'] = ApiClient.convertToType(data['encoding'], 'String');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
        }
        return obj;
    }


}

/**
 * MIME version. By default set to `1.0`
 * @member {String} version
 */
V4MessagesBodyParts.prototype['version'] = undefined;

/**
 * MIME type. By default set to `plain/text`
 * @member {String} type
 */
V4MessagesBodyParts.prototype['type'] = undefined;

/**
 * Content character set -- i.e. UTF-8, ISO-8859-1, etc.
 * @member {String} charset
 */
V4MessagesBodyParts.prototype['charset'] = undefined;

/**
 * Content encoding – i.e. 7bit, quoted-printable, base64, etc. default base64
 * @member {String} encoding
 */
V4MessagesBodyParts.prototype['encoding'] = undefined;

/**
 * Actual part’s content in its raw form
 * @member {String} content
 */
V4MessagesBodyParts.prototype['content'] = undefined;






export default V4MessagesBodyParts;

