/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Account from '../model/Account';
import BadRequestSchema from '../model/BadRequestSchema';
import InvalidKey from '../model/InvalidKey';
import UpdateAccountResponse from '../model/UpdateAccountResponse';

/**
* Account service.
* @module api/AccountApi
* @version 4.0.0
*/
export default class AccountApi {

    /**
    * Constructs a new AccountApi. 
    * @alias module:api/AccountApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the v4AccountContactPatch operation.
     * @callback module:api/AccountApi~v4AccountContactPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/UpdateAccountResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Account Details
     * @param {Object} opts Optional parameters
     * @param {String} opts.firstName First name of account owner
     * @param {String} opts.lastName Last name of account owner
     * @param {String} opts.email Email address of account owner
     * @param {String} opts.companyName Account owner’s company name
     * @param {String} opts.phone Phone number of account owner
     * @param {String} opts.website Website of account owner
     * @param {String} opts.addressStreet Account owner’s street address
     * @param {String} opts.addressCity Account owner’s city
     * @param {String} opts.addressState Account owner’s state
     * @param {String} opts.addressCountry Account owner’s country
     * @param {module:api/AccountApi~v4AccountContactPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/UpdateAccountResponse}
     */
    v4AccountContactPatch(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'first_name': opts['firstName'],
        'last_name': opts['lastName'],
        'email': opts['email'],
        'company_name': opts['companyName'],
        'phone': opts['phone'],
        'website': opts['website'],
        'address.street': opts['addressStreet'],
        'address.city': opts['addressCity'],
        'address.state': opts['addressState'],
        'address.country': opts['addressCountry']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = UpdateAccountResponse;
      return this.apiClient.callApi(
        '/v4/account/contact', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4AccountGet operation.
     * @callback module:api/AccountApi~v4AccountGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Account} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Account Details
     * @param {module:api/AccountApi~v4AccountGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Account}
     */
    v4AccountGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Account;
      return this.apiClient.callApi(
        '/v4/account/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
