/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import BadRequestSchema from '../model/BadRequestSchema';
import GetAlertDetails from '../model/GetAlertDetails';
import GetAlertResponse from '../model/GetAlertResponse';
import InvalidKey from '../model/InvalidKey';
import StatusResponse from '../model/StatusResponse';

/**
* Alerts service.
* @module api/AlertsApi
* @version 4.0.0
*/
export default class AlertsApi {

    /**
    * Constructs a new AlertsApi. 
    * @alias module:api/AlertsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the v4AlertsAlertIdDelete operation.
     * @callback module:api/AlertsApi~v4AlertsAlertIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/StatusResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Alert
     * @param {String} alertId Id of a given alert
     * @param {module:api/AlertsApi~v4AlertsAlertIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/StatusResponse}
     */
    v4AlertsAlertIdDelete(alertId, callback) {
      let postBody = null;
      // verify the required parameter 'alertId' is set
      if (alertId === undefined || alertId === null) {
        throw new Error("Missing the required parameter 'alertId' when calling v4AlertsAlertIdDelete");
      }

      let pathParams = {
        'alert_id': alertId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = StatusResponse;
      return this.apiClient.callApi(
        '/v4/alerts/{alert_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4AlertsAlertIdGet operation.
     * @callback module:api/AlertsApi~v4AlertsAlertIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetAlertDetails} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Alert Details
     * @param {String} alertId Id of a given alert
     * @param {module:api/AlertsApi~v4AlertsAlertIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetAlertDetails}
     */
    v4AlertsAlertIdGet(alertId, callback) {
      let postBody = null;
      // verify the required parameter 'alertId' is set
      if (alertId === undefined || alertId === null) {
        throw new Error("Missing the required parameter 'alertId' when calling v4AlertsAlertIdGet");
      }

      let pathParams = {
        'alert_id': alertId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetAlertDetails;
      return this.apiClient.callApi(
        '/v4/alerts/{alert_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4AlertsAlertIdPatch operation.
     * @callback module:api/AlertsApi~v4AlertsAlertIdPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/StatusResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Alert Details
     * @param {String} alertId Id of a given alert
     * @param {Object} opts Optional parameters
     * @param {module:model/Number} opts.threshold A number which represents a percentage of an account’s monthly quota. Must be decimal between 0 and 1
     * @param {module:api/AlertsApi~v4AlertsAlertIdPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/StatusResponse}
     */
    v4AlertsAlertIdPatch(alertId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'alertId' is set
      if (alertId === undefined || alertId === null) {
        throw new Error("Missing the required parameter 'alertId' when calling v4AlertsAlertIdPatch");
      }

      let pathParams = {
        'alert_id': alertId
      };
      let queryParams = {
        'threshold': opts['threshold']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = StatusResponse;
      return this.apiClient.callApi(
        '/v4/alerts/{alert_id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4AlertsGet operation.
     * @callback module:api/AlertsApi~v4AlertsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetAlertResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List All Allerts
     * @param {module:api/AlertsApi~v4AlertsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetAlertResponse}
     */
    v4AlertsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetAlertResponse;
      return this.apiClient.callApi(
        '/v4/alerts/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4AlertsPost operation.
     * @callback module:api/AlertsApi~v4AlertsPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/StatusResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create New Alert
     * @param {module:model/String} type An alert’s type. Currently only “monthly_quota” is supported
     * @param {Object} opts Optional parameters
     * @param {module:model/Number} opts.threshold A number which represents a percentage of an account’s monthly quota. Must be decimal between 0 and 1
     * @param {module:api/AlertsApi~v4AlertsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/StatusResponse}
     */
    v4AlertsPost(type, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'type' is set
      if (type === undefined || type === null) {
        throw new Error("Missing the required parameter 'type' when calling v4AlertsPost");
      }

      let pathParams = {
      };
      let queryParams = {
        'type': type,
        'threshold': opts['threshold']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = StatusResponse;
      return this.apiClient.callApi(
        '/v4/alerts/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
