/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import APIKey from '../model/APIKey';
import BadRequestSchema from '../model/BadRequestSchema';
import GetApiKeys from '../model/GetApiKeys';
import InvalidKey from '../model/InvalidKey';
import StatusResponse from '../model/StatusResponse';

/**
* APIKeys service.
* @module api/APIKeysApi
* @version 4.0.0
*/
export default class APIKeysApi {

    /**
    * Constructs a new APIKeysApi. 
    * @alias module:api/APIKeysApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getAPIKey operation.
     * @callback module:api/APIKeysApi~getAPIKeyCallback
     * @param {String} error Error message, if any.
     * @param {module:model/APIKey} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get API Key Details
     * @param {String} apiKey API Key Identificator.
     * @param {module:api/APIKeysApi~getAPIKeyCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/APIKey}
     */
    getAPIKey(apiKey, callback) {
      let postBody = null;
      // verify the required parameter 'apiKey' is set
      if (apiKey === undefined || apiKey === null) {
        throw new Error("Missing the required parameter 'apiKey' when calling getAPIKey");
      }

      let pathParams = {
        'api_key': apiKey
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = APIKey;
      return this.apiClient.callApi(
        '/v4/api_keys/{api_key}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4ApiKeysApiKeyDelete operation.
     * @callback module:api/APIKeysApi~v4ApiKeysApiKeyDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/StatusResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete an API Key
     * @param {String} apiKey API key value
     * @param {module:api/APIKeysApi~v4ApiKeysApiKeyDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/StatusResponse}
     */
    v4ApiKeysApiKeyDelete(apiKey, callback) {
      let postBody = null;
      // verify the required parameter 'apiKey' is set
      if (apiKey === undefined || apiKey === null) {
        throw new Error("Missing the required parameter 'apiKey' when calling v4ApiKeysApiKeyDelete");
      }

      let pathParams = {
        'api_key': apiKey
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = StatusResponse;
      return this.apiClient.callApi(
        '/v4/api_keys/{api_key}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4ApiKeysApiKeyPatch operation.
     * @callback module:api/APIKeysApi~v4ApiKeysApiKeyPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/APIKey} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update API Key
     * @param {String} apiKey API key value
     * @param {Object} opts Optional parameters
     * @param {String} opts.name Name for API key
     * @param {String} opts.description Description for API Key
     * @param {module:api/APIKeysApi~v4ApiKeysApiKeyPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/APIKey}
     */
    v4ApiKeysApiKeyPatch(apiKey, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'apiKey' is set
      if (apiKey === undefined || apiKey === null) {
        throw new Error("Missing the required parameter 'apiKey' when calling v4ApiKeysApiKeyPatch");
      }

      let pathParams = {
        'api_key': apiKey
      };
      let queryParams = {
        'name': opts['name'],
        'description': opts['description']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = APIKey;
      return this.apiClient.callApi(
        '/v4/api_keys/{api_key}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4ApiKeysGet operation.
     * @callback module:api/APIKeysApi~v4ApiKeysGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetApiKeys} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List All API Keys
     * @param {module:api/APIKeysApi~v4ApiKeysGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetApiKeys}
     */
    v4ApiKeysGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetApiKeys;
      return this.apiClient.callApi(
        '/v4/api_keys/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4ApiKeysPost operation.
     * @callback module:api/APIKeysApi~v4ApiKeysPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/APIKey} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a New API Key
     * @param {String} name Name for API key
     * @param {Object} opts Optional parameters
     * @param {String} opts.description Description for API key
     * @param {module:api/APIKeysApi~v4ApiKeysPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/APIKey}
     */
    v4ApiKeysPost(name, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling v4ApiKeysPost");
      }

      let pathParams = {
      };
      let queryParams = {
        'name': name,
        'description': opts['description']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = APIKey;
      return this.apiClient.callApi(
        '/v4/api_keys/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
