/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import BadRequestSchema from '../model/BadRequestSchema';
import CreateCallbackResponse from '../model/CreateCallbackResponse';
import GetCallbackDetails from '../model/GetCallbackDetails';
import GetCallbackLogs from '../model/GetCallbackLogs';
import GetCallbackResponse from '../model/GetCallbackResponse';
import InvalidKey from '../model/InvalidKey';
import StatusResponse from '../model/StatusResponse';

/**
* Callbacks service.
* @module api/CallbacksApi
* @version 4.0.0
*/
export default class CallbacksApi {

    /**
    * Constructs a new CallbacksApi. 
    * @alias module:api/CallbacksApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the v4CallbacksDelete operation.
     * @callback module:api/CallbacksApi~v4CallbacksDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/StatusResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete All Callbacks
     * @param {module:api/CallbacksApi~v4CallbacksDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/StatusResponse}
     */
    v4CallbacksDelete(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = StatusResponse;
      return this.apiClient.callApi(
        '/v4/callbacks/', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4CallbacksEventDelete operation.
     * @callback module:api/CallbacksApi~v4CallbacksEventDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/StatusResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Callback
     * @param {module:model/String} event Event for which the callback has been created. Valid types are:  * delivered -  message delivered * failed - message bounced * complained - complaint received * bounceback - bounce back notification received * received - message received by our system * queued - message in queue (transient) * hard_bounced - hard bounce received * opened - message opened * clicked - URL in message clicked * unsubscribed - unsubscribe received 
     * @param {String} channel Name of the channel for which the callback has been created
     * @param {module:api/CallbacksApi~v4CallbacksEventDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/StatusResponse}
     */
    v4CallbacksEventDelete(event, channel, callback) {
      let postBody = null;
      // verify the required parameter 'event' is set
      if (event === undefined || event === null) {
        throw new Error("Missing the required parameter 'event' when calling v4CallbacksEventDelete");
      }
      // verify the required parameter 'channel' is set
      if (channel === undefined || channel === null) {
        throw new Error("Missing the required parameter 'channel' when calling v4CallbacksEventDelete");
      }

      let pathParams = {
        'event': event
      };
      let queryParams = {
        'channel': channel
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = StatusResponse;
      return this.apiClient.callApi(
        '/v4/callbacks/{event}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4CallbacksEventGet operation.
     * @callback module:api/CallbacksApi~v4CallbacksEventGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetCallbackDetails} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Callback Details
     * @param {module:model/String} event Event for which the callback has been created. Valid types are:  * delivered -  message delivered * failed - message bounced * complained - complaint received * bounceback - bounce back notification received * received - message received by our system * queued - message in queue (transient) * hard_bounced - hard bounce received * opened - message opened * clicked - URL in message clicked * unsubscribed - unsubscribe received 
     * @param {String} channel Name of the channel for which the callback has been created
     * @param {module:api/CallbacksApi~v4CallbacksEventGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetCallbackDetails}
     */
    v4CallbacksEventGet(event, channel, callback) {
      let postBody = null;
      // verify the required parameter 'event' is set
      if (event === undefined || event === null) {
        throw new Error("Missing the required parameter 'event' when calling v4CallbacksEventGet");
      }
      // verify the required parameter 'channel' is set
      if (channel === undefined || channel === null) {
        throw new Error("Missing the required parameter 'channel' when calling v4CallbacksEventGet");
      }

      let pathParams = {
        'event': event
      };
      let queryParams = {
        'channel': channel
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetCallbackDetails;
      return this.apiClient.callApi(
        '/v4/callbacks/{event}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4CallbacksEventPatch operation.
     * @callback module:api/CallbacksApi~v4CallbacksEventPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/StatusResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Callback Details
     * @param {module:model/String} event Event for which the callback should be created. Valid types are:  * delivered -  message delivered * failed - message bounced * complained - complaint received * bounceback - bounce back notification received * received - message received by our system * queued - message in queue (transient) * hard_bounced - hard bounce received * opened - message opened * clicked - URL in message clicked * unsubscribed - unsubscribe received 
     * @param {String} channel Name of the channel for which the callback has been created
     * @param {Object} opts Optional parameters
     * @param {String} opts.medium Medium by which the callback data is sent. Possible values are one of:   * http   * aws 
     * @param {String} opts.address Address to which the callback data is sent. This will be either a URL for http-based callbacks or the Amazon SQS queue name for SQS-based callbacks
     * @param {String} opts.awsData Amazon SQS settings. ``` {key:string, secret:string} ``` must be provided if medium is of type sqs 
     * @param {module:api/CallbacksApi~v4CallbacksEventPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/StatusResponse}
     */
    v4CallbacksEventPatch(event, channel, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'event' is set
      if (event === undefined || event === null) {
        throw new Error("Missing the required parameter 'event' when calling v4CallbacksEventPatch");
      }
      // verify the required parameter 'channel' is set
      if (channel === undefined || channel === null) {
        throw new Error("Missing the required parameter 'channel' when calling v4CallbacksEventPatch");
      }

      let pathParams = {
        'event': event
      };
      let queryParams = {
        'channel': channel,
        'medium': opts['medium'],
        'address': opts['address'],
        'aws_data': opts['awsData']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = StatusResponse;
      return this.apiClient.callApi(
        '/v4/callbacks/{event}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4CallbacksEventPost operation.
     * @callback module:api/CallbacksApi~v4CallbacksEventPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateCallbackResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create Callback
     * @param {module:model/String} event Event for which the callback should be created. Valid types are:  * delivered -  message delivered * failed - message bounced * complained - complaint received * bounceback - bounce back notification received * received - message received by our system * queued - message in queue (transient) * hard_bounced - hard bounce received * opened - message opened * clicked - URL in message clicked * unsubscribed - unsubscribe received 
     * @param {String} channel Name of the channel for which the callback has been created.
     * @param {String} medium Medium to send callback data. Valid values are one of:   * http   * sqs 
     * @param {String} address Address of where the callback data should be sent. This will be either a URL for http-based callbacks or the Amazon SQS queue name for SQS-based callbacks.
     * @param {Object} opts Optional parameters
     * @param {String} opts.awsData Amazon SQS settings. ``` {key:string, secret:string} ``` must be provided if medium is of type sqs 
     * @param {module:api/CallbacksApi~v4CallbacksEventPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateCallbackResponse}
     */
    v4CallbacksEventPost(event, channel, medium, address, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'event' is set
      if (event === undefined || event === null) {
        throw new Error("Missing the required parameter 'event' when calling v4CallbacksEventPost");
      }
      // verify the required parameter 'channel' is set
      if (channel === undefined || channel === null) {
        throw new Error("Missing the required parameter 'channel' when calling v4CallbacksEventPost");
      }
      // verify the required parameter 'medium' is set
      if (medium === undefined || medium === null) {
        throw new Error("Missing the required parameter 'medium' when calling v4CallbacksEventPost");
      }
      // verify the required parameter 'address' is set
      if (address === undefined || address === null) {
        throw new Error("Missing the required parameter 'address' when calling v4CallbacksEventPost");
      }

      let pathParams = {
        'event': event
      };
      let queryParams = {
        'channel': channel,
        'medium': medium,
        'address': address,
        'aws_data': opts['awsData']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CreateCallbackResponse;
      return this.apiClient.callApi(
        '/v4/callbacks/{event}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4CallbacksGet operation.
     * @callback module:api/CallbacksApi~v4CallbacksGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetCallbackResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List All Callbacks
     * @param {module:api/CallbacksApi~v4CallbacksGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetCallbackResponse}
     */
    v4CallbacksGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetCallbackResponse;
      return this.apiClient.callApi(
        '/v4/callbacks/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4CallbacksLogGet operation.
     * @callback module:api/CallbacksApi~v4CallbacksLogGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetCallbackLogs} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * View Callback Logs
     * Review all callback logs for a specific channel. It may help debug issues related to receiving callbacks on a user's side.
     * @param {String} channel Name of the channel for which the given callback has been created
     * @param {Object} opts Optional parameters
     * @param {Number} opts.limit Number of items to return in the response. Default is 20
     * @param {module:api/CallbacksApi~v4CallbacksLogGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetCallbackLogs}
     */
    v4CallbacksLogGet(channel, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'channel' is set
      if (channel === undefined || channel === null) {
        throw new Error("Missing the required parameter 'channel' when calling v4CallbacksLogGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'channel': channel,
        'limit': opts['limit']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetCallbackLogs;
      return this.apiClient.callApi(
        '/v4/callbacks/log', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
