/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import BadRequestSchema from '../model/BadRequestSchema';
import Channel from '../model/Channel';
import Channels from '../model/Channels';
import InvalidKey from '../model/InvalidKey';

/**
* Channels service.
* @module api/ChannelsApi
* @version 4.0.0
*/
export default class ChannelsApi {

    /**
    * Constructs a new ChannelsApi. 
    * @alias module:api/ChannelsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getSender operation.
     * @callback module:api/ChannelsApi~getSenderCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Channel} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Channel Details
     * **Note:** This method doesn't return archived channels. 
     * @param {String} name Name of the channel (sender)
     * @param {module:api/ChannelsApi~getSenderCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Channel}
     */
    getSender(name, callback) {
      let postBody = null;
      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling getSender");
      }

      let pathParams = {
        'name': name
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Channel;
      return this.apiClient.callApi(
        '/v4/channels/{name}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4ChannelsGet operation.
     * @callback module:api/ChannelsApi~v4ChannelsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Channels} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get All Channels
     * **Note:** This method does not return archived channels. 
     * @param {module:api/ChannelsApi~v4ChannelsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Channels}
     */
    v4ChannelsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Channels;
      return this.apiClient.callApi(
        '/v4/channels/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4ChannelsNameDelete operation.
     * @callback module:api/ChannelsApi~v4ChannelsNameDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Channel} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a Channel
     * **Note:** This method doesn’t permanently delete the channel but rather sets the status to “canceled”. 
     * @param {String} name Name of the channel (sender)
     * @param {module:api/ChannelsApi~v4ChannelsNameDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Channel}
     */
    v4ChannelsNameDelete(name, callback) {
      let postBody = null;
      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling v4ChannelsNameDelete");
      }

      let pathParams = {
        'name': name
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Channel;
      return this.apiClient.callApi(
        '/v4/channels/{name}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4ChannelsNamePatch operation.
     * @callback module:api/ChannelsApi~v4ChannelsNamePatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Channel} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Channel Details
     * @param {String} name Name of the channel (sender)
     * @param {Object} opts Optional parameters
     * @param {String} opts.smtpUsername Username for the channel
     * @param {String} opts.smtpPassword Password for the channel
     * @param {Number} opts.quota Quota for the channel
     * @param {module:api/ChannelsApi~v4ChannelsNamePatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Channel}
     */
    v4ChannelsNamePatch(name, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling v4ChannelsNamePatch");
      }

      let pathParams = {
        'name': name
      };
      let queryParams = {
        'smtp_username': opts['smtpUsername'],
        'smtp_password': opts['smtpPassword'],
        'quota': opts['quota']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Channel;
      return this.apiClient.callApi(
        '/v4/channels/{name}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4ChannelsPost operation.
     * @callback module:api/ChannelsApi~v4ChannelsPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Channel} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a New Channel
     * @param {String} name Name of the channel (sender)
     * @param {String} smtpUsername Username for the channel
     * @param {String} smtpPassword Password for the channel
     * @param {Number} quota Quota for the channel
     * @param {module:api/ChannelsApi~v4ChannelsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Channel}
     */
    v4ChannelsPost(name, smtpUsername, smtpPassword, quota, callback) {
      let postBody = null;
      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling v4ChannelsPost");
      }
      // verify the required parameter 'smtpUsername' is set
      if (smtpUsername === undefined || smtpUsername === null) {
        throw new Error("Missing the required parameter 'smtpUsername' when calling v4ChannelsPost");
      }
      // verify the required parameter 'smtpPassword' is set
      if (smtpPassword === undefined || smtpPassword === null) {
        throw new Error("Missing the required parameter 'smtpPassword' when calling v4ChannelsPost");
      }
      // verify the required parameter 'quota' is set
      if (quota === undefined || quota === null) {
        throw new Error("Missing the required parameter 'quota' when calling v4ChannelsPost");
      }

      let pathParams = {
      };
      let queryParams = {
        'name': name,
        'smtp_username': smtpUsername,
        'smtp_password': smtpPassword,
        'quota': quota
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Channel;
      return this.apiClient.callApi(
        '/v4/channels/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
