/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import BadRequestSchema from '../model/BadRequestSchema';
import CreateDkimKey from '../model/CreateDkimKey';
import CreateDomainResponse from '../model/CreateDomainResponse';
import GetDomainDetails from '../model/GetDomainDetails';
import GetDomainDetailsResponse from '../model/GetDomainDetailsResponse';
import GetDomainsResponse from '../model/GetDomainsResponse';
import InvalidKey from '../model/InvalidKey';
import StatusResponse from '../model/StatusResponse';

/**
* DKIMs service.
* @module api/DKIMsApi
* @version 4.0.0
*/
export default class DKIMsApi {

    /**
    * Constructs a new DKIMsApi. 
    * @alias module:api/DKIMsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the v4DomainsDomainNameDelete operation.
     * @callback module:api/DKIMsApi~v4DomainsDomainNameDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/StatusResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Domain
     * Deletes a domain that was previously registered by the current account.
     * @param {String} domainName Domain name of interest
     * @param {module:api/DKIMsApi~v4DomainsDomainNameDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/StatusResponse}
     */
    v4DomainsDomainNameDelete(domainName, callback) {
      let postBody = null;
      // verify the required parameter 'domainName' is set
      if (domainName === undefined || domainName === null) {
        throw new Error("Missing the required parameter 'domainName' when calling v4DomainsDomainNameDelete");
      }

      let pathParams = {
        'domain_name': domainName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = StatusResponse;
      return this.apiClient.callApi(
        '/v4/domains/{domain_name}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4DomainsDomainNameDkimKeysDelete operation.
     * @callback module:api/DKIMsApi~v4DomainsDomainNameDkimKeysDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/StatusResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete DKIM for Domain
     * @param {String} domainName Domain name of interest
     * @param {module:api/DKIMsApi~v4DomainsDomainNameDkimKeysDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/StatusResponse}
     */
    v4DomainsDomainNameDkimKeysDelete(domainName, callback) {
      let postBody = null;
      // verify the required parameter 'domainName' is set
      if (domainName === undefined || domainName === null) {
        throw new Error("Missing the required parameter 'domainName' when calling v4DomainsDomainNameDkimKeysDelete");
      }

      let pathParams = {
        'domain_name': domainName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = StatusResponse;
      return this.apiClient.callApi(
        '/v4/domains/{domain_name}/dkim_keys', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4DomainsDomainNameDkimKeysGet operation.
     * @callback module:api/DKIMsApi~v4DomainsDomainNameDkimKeysGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetDomainDetails} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get DKIM for Domain
     * @param {String} domainName Domain name of interest
     * @param {module:api/DKIMsApi~v4DomainsDomainNameDkimKeysGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetDomainDetails}
     */
    v4DomainsDomainNameDkimKeysGet(domainName, callback) {
      let postBody = null;
      // verify the required parameter 'domainName' is set
      if (domainName === undefined || domainName === null) {
        throw new Error("Missing the required parameter 'domainName' when calling v4DomainsDomainNameDkimKeysGet");
      }

      let pathParams = {
        'domain_name': domainName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetDomainDetails;
      return this.apiClient.callApi(
        '/v4/domains/{domain_name}/dkim_keys', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4DomainsDomainNameDkimKeysPatch operation.
     * @callback module:api/DKIMsApi~v4DomainsDomainNameDkimKeysPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/StatusResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update DKIM Key Details
     * @param {String} domainName Domain name of interest
     * @param {String} selector Name of DKIM selector for this domain
     * @param {String} privateKey Private key of the DKIM record
     * @param {module:api/DKIMsApi~v4DomainsDomainNameDkimKeysPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/StatusResponse}
     */
    v4DomainsDomainNameDkimKeysPatch(domainName, selector, privateKey, callback) {
      let postBody = null;
      // verify the required parameter 'domainName' is set
      if (domainName === undefined || domainName === null) {
        throw new Error("Missing the required parameter 'domainName' when calling v4DomainsDomainNameDkimKeysPatch");
      }
      // verify the required parameter 'selector' is set
      if (selector === undefined || selector === null) {
        throw new Error("Missing the required parameter 'selector' when calling v4DomainsDomainNameDkimKeysPatch");
      }
      // verify the required parameter 'privateKey' is set
      if (privateKey === undefined || privateKey === null) {
        throw new Error("Missing the required parameter 'privateKey' when calling v4DomainsDomainNameDkimKeysPatch");
      }

      let pathParams = {
        'domain_name': domainName
      };
      let queryParams = {
        'selector': selector,
        'private_key': privateKey
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = StatusResponse;
      return this.apiClient.callApi(
        '/v4/domains/{domain_name}/dkim_keys', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4DomainsDomainNameDkimKeysPost operation.
     * @callback module:api/DKIMsApi~v4DomainsDomainNameDkimKeysPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateDkimKey} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add DKIM for Domain
     * @param {String} domainName Domain name of interest
     * @param {String} selector Name of DKIM selector for this domain
     * @param {String} privateKey Private key of the DKIM record
     * @param {module:api/DKIMsApi~v4DomainsDomainNameDkimKeysPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateDkimKey}
     */
    v4DomainsDomainNameDkimKeysPost(domainName, selector, privateKey, callback) {
      let postBody = null;
      // verify the required parameter 'domainName' is set
      if (domainName === undefined || domainName === null) {
        throw new Error("Missing the required parameter 'domainName' when calling v4DomainsDomainNameDkimKeysPost");
      }
      // verify the required parameter 'selector' is set
      if (selector === undefined || selector === null) {
        throw new Error("Missing the required parameter 'selector' when calling v4DomainsDomainNameDkimKeysPost");
      }
      // verify the required parameter 'privateKey' is set
      if (privateKey === undefined || privateKey === null) {
        throw new Error("Missing the required parameter 'privateKey' when calling v4DomainsDomainNameDkimKeysPost");
      }

      let pathParams = {
        'domain_name': domainName
      };
      let queryParams = {
        'selector': selector,
        'private_key': privateKey
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CreateDkimKey;
      return this.apiClient.callApi(
        '/v4/domains/{domain_name}/dkim_keys', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4DomainsDomainNameGet operation.
     * @callback module:api/DKIMsApi~v4DomainsDomainNameGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetDomainDetailsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Domain Details
     * @param {String} domainName Domain name of interest
     * @param {module:api/DKIMsApi~v4DomainsDomainNameGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetDomainDetailsResponse}
     */
    v4DomainsDomainNameGet(domainName, callback) {
      let postBody = null;
      // verify the required parameter 'domainName' is set
      if (domainName === undefined || domainName === null) {
        throw new Error("Missing the required parameter 'domainName' when calling v4DomainsDomainNameGet");
      }

      let pathParams = {
        'domain_name': domainName
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetDomainDetailsResponse;
      return this.apiClient.callApi(
        '/v4/domains/{domain_name}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4DomainsDomainNamePatch operation.
     * @callback module:api/DKIMsApi~v4DomainsDomainNamePatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/StatusResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Domain Details
     * @param {String} domainName Domain name of interest
     * @param {Boolean} enabled Whether the domain is enabled
     * @param {module:api/DKIMsApi~v4DomainsDomainNamePatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/StatusResponse}
     */
    v4DomainsDomainNamePatch(domainName, enabled, callback) {
      let postBody = null;
      // verify the required parameter 'domainName' is set
      if (domainName === undefined || domainName === null) {
        throw new Error("Missing the required parameter 'domainName' when calling v4DomainsDomainNamePatch");
      }
      // verify the required parameter 'enabled' is set
      if (enabled === undefined || enabled === null) {
        throw new Error("Missing the required parameter 'enabled' when calling v4DomainsDomainNamePatch");
      }

      let pathParams = {
        'domain_name': domainName
      };
      let queryParams = {
        'enabled': enabled
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = StatusResponse;
      return this.apiClient.callApi(
        '/v4/domains/{domain_name}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4DomainsGet operation.
     * @callback module:api/DKIMsApi~v4DomainsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetDomainsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get All Registered Domains
     * Returns all domains registered by this account
     * @param {module:api/DKIMsApi~v4DomainsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetDomainsResponse}
     */
    v4DomainsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetDomainsResponse;
      return this.apiClient.callApi(
        '/v4/domains/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4DomainsPost operation.
     * @callback module:api/DKIMsApi~v4DomainsPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CreateDomainResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Register a Domain
     * Add a new domain to the list of account's registered domains
     * @param {String} domainName Domain name to add
     * @param {module:api/DKIMsApi~v4DomainsPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CreateDomainResponse}
     */
    v4DomainsPost(domainName, callback) {
      let postBody = null;
      // verify the required parameter 'domainName' is set
      if (domainName === undefined || domainName === null) {
        throw new Error("Missing the required parameter 'domainName' when calling v4DomainsPost");
      }

      let pathParams = {
      };
      let queryParams = {
        'domain_name': domainName
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CreateDomainResponse;
      return this.apiClient.callApi(
        '/v4/domains/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
