/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import BadRequestSchema from '../model/BadRequestSchema';
import InlineObject from '../model/InlineObject';
import InlineObject1 from '../model/InlineObject1';
import InvalidKey from '../model/InvalidKey';
import MessagesResponse from '../model/MessagesResponse';
import MimeResponse from '../model/MimeResponse';
import PostMessageResponse from '../model/PostMessageResponse';

/**
* Messages service.
* @module api/MessagesApi
* @version 4.0.0
*/
export default class MessagesApi {

    /**
    * Constructs a new MessagesApi. 
    * @alias module:api/MessagesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the v4MessagesGet operation.
     * @callback module:api/MessagesApi~v4MessagesGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MessagesResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Detailed Messages Info
     * @param {String} start The starting time. RFC 2822 or UNIX epoch format
     * @param {Number} limit Maximum number of items to return.
     * @param {Number} offset Number of items to skip before returning the results.
     * @param {String} channel Name of  the channel used to send messages
     * @param {Object} opts Optional parameters
     * @param {String} opts.end The ending time. If not specified, defaults to now. RFC 2822 or UNIX epoch format.
     * @param {module:model/String} opts.event Array of any event names for which stats has been requested ('accepted', 'failed', 'delivered').
     * @param {String} opts.msgId Unique message ID
     * @param {module:api/MessagesApi~v4MessagesGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MessagesResponse}
     */
    v4MessagesGet(start, limit, offset, channel, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'start' is set
      if (start === undefined || start === null) {
        throw new Error("Missing the required parameter 'start' when calling v4MessagesGet");
      }
      // verify the required parameter 'limit' is set
      if (limit === undefined || limit === null) {
        throw new Error("Missing the required parameter 'limit' when calling v4MessagesGet");
      }
      // verify the required parameter 'offset' is set
      if (offset === undefined || offset === null) {
        throw new Error("Missing the required parameter 'offset' when calling v4MessagesGet");
      }
      // verify the required parameter 'channel' is set
      if (channel === undefined || channel === null) {
        throw new Error("Missing the required parameter 'channel' when calling v4MessagesGet");
      }

      let pathParams = {
      };
      let queryParams = {
        'start': start,
        'end': opts['end'],
        'event': opts['event'],
        'limit': limit,
        'offset': offset,
        'msg_id': opts['msgId'],
        'channel': channel
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = MessagesResponse;
      return this.apiClient.callApi(
        '/v4/messages', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4MessagesMimePost operation.
     * @callback module:api/MessagesApi~v4MessagesMimePostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/MimeResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Send MIME Message
     * This method will send a prepared RFC compliant MIME message via a specified channel **Note:** All restrictions from the section entitled `Send a Message` are implied here. 
     * @param {module:model/InlineObject1} inlineObject1 
     * @param {module:api/MessagesApi~v4MessagesMimePostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/MimeResponse}
     */
    v4MessagesMimePost(inlineObject1, callback) {
      let postBody = inlineObject1;
      // verify the required parameter 'inlineObject1' is set
      if (inlineObject1 === undefined || inlineObject1 === null) {
        throw new Error("Missing the required parameter 'inlineObject1' when calling v4MessagesMimePost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = MimeResponse;
      return this.apiClient.callApi(
        '/v4/messages/mime', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4MessagesPost operation.
     * @callback module:api/MessagesApi~v4MessagesPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PostMessageResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Send a Message
     * Send a message over HTTP/HTTPS protocol using a specified channel. The request can generate only an HTTP 400 error and will return validation error data. The actual suppression, delivery attempt or SMTP error can be received via callbacks. See the section on Callbacks for more details.  <br> **Limitations:** * The number of recipients in a single email request is limited to `1000` (including to, cc and bcc) * The total payload of the generated MIME message cannot exceed `10Mb` in size  <br> **Notes:** * When JUST two parts provided with `text/plain` and `text/html` types, they are automatically wrapped into a `mime/alternative` container * Adding any other part or attachment to either a single part or attachment or `mime/alternative` automatically wraps all mime containers into a `mime/mixed` container * Content type message/rfc822 is prohibited 
     * @param {Object} opts Optional parameters
     * @param {module:model/InlineObject} opts.inlineObject 
     * @param {module:api/MessagesApi~v4MessagesPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PostMessageResponse}
     */
    v4MessagesPost(opts, callback) {
      opts = opts || {};
      let postBody = opts['inlineObject'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PostMessageResponse;
      return this.apiClient.callApi(
        '/v4/messages', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
