/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import BadRequestSchema from '../model/BadRequestSchema';
import InvalidKey from '../model/InvalidKey';
import Report from '../model/Report';
import Reports from '../model/Reports';
import StatusResponse from '../model/StatusResponse';

/**
* Reports service.
* @module api/ReportsApi
* @version 4.0.0
*/
export default class ReportsApi {

    /**
    * Constructs a new ReportsApi. 
    * @alias module:api/ReportsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the v4ReportsGet operation.
     * @callback module:api/ReportsApi~v4ReportsGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Reports} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get All Reports
     * @param {module:api/ReportsApi~v4ReportsGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Reports}
     */
    v4ReportsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Reports;
      return this.apiClient.callApi(
        '/v4/reports/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4ReportsOndemandPost operation.
     * @callback module:api/ReportsApi~v4ReportsOndemandPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/StatusResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create On-Demand Report
     * @param {Number} start Start date/time of the report in RFC 2822 or UNIX epoch format
     * @param {Object} opts Optional parameters
     * @param {String} opts.channel Name of the channel for which a given report has been defined
     * @param {module:model/String} opts.type Type or report format. If not specified defaults to “csv” - currently the only supported type
     * @param {String} opts.end End date/time of the report in RFC 2822 or UNIX epoch format (default - now)
     * @param {String} opts.domain Filter by the “from” domain of emails
     * @param {String} opts.rcptDomain Filter by the “to” domain of emails
     * @param {String} opts.events Filter by event type. Valid event are:  * hard_bounced - just hard bounces * failed - all failed messages, i.e. hard_bounced + the rest of failed * delivered - delivered messages * sent - delivered+failed (default events value) * pending - pending messages * total - all messages, i.e. sent+pending * abuse - spam complaints 
     * @param {String} opts.columns Array of columns to be specified in the report. These can differ based on any specified event type filter.   Possible column values for all reports are: * `message_id` - Unique message ID * from - From Address * to - Recipient Address * time_rcv - Date Received in RFC 2822 or UNIX epoch format * time_snt - Date Delivered in RFC 2822 or UNIX epoch format * channel - Name of a channel  Additional column values for message reports (hard_bounced, failed, delivered, total) include: * status - Status of delivery * code - SMTP Response Code * message - SMTP Response message * tries - Amount of re-tries (deferred states before final)  Additional column values for spam reports include:  * report_time - Date when an abuse complaint has been reported, RFC 2822 or UNIX epoch format * subject - Email Subject  Additional column values for pending reports include:  * status - Current email status  If not specified all relevant columns are included. 
     * @param {module:api/ReportsApi~v4ReportsOndemandPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/StatusResponse}
     */
    v4ReportsOndemandPost(start, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'start' is set
      if (start === undefined || start === null) {
        throw new Error("Missing the required parameter 'start' when calling v4ReportsOndemandPost");
      }

      let pathParams = {
      };
      let queryParams = {
        'channel': opts['channel'],
        'type': opts['type'],
        'start': start,
        'end': opts['end'],
        'domain': opts['domain'],
        'rcpt_domain': opts['rcptDomain'],
        'events': opts['events'],
        'columns': opts['columns']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = StatusResponse;
      return this.apiClient.callApi(
        '/v4/reports/ondemand', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4ReportsPeriodicPost operation.
     * @callback module:api/ReportsApi~v4ReportsPeriodicPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/StatusResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create Periodic Report
     * @param {module:model/String} frequency Report frequency – one of:   * daily - every day at a specified hour   * weekly  - Mondays at a specified hour   * monthly - 1st day of the month at a specified hour 
     * @param {Number} reportTime The hour at which the report should be sent. Value values range from 0 to 23
     * @param {Object} opts Optional parameters
     * @param {String} opts.channel Name of the channel for which a given report has been defined
     * @param {module:model/String} opts.notifyMethod Notification method to be used when report is completed and can be downloaded
     * @param {String} opts.notifyDest A valid URL which will accept the report completion notification. The payload will be ```   {\"message\": \"success\", \"id\": string} ``` where `id` is a Unique report ID 
     * @param {String} opts.domain Filter by the “From” domain of emails
     * @param {String} opts.rcptDomain Filter by the “To” domain of emails
     * @param {String} opts.events Filter by event type. Valid event are:  * hard_bounced - just hard bounces * failed - all failed messages, i.e. hard_bounced + the rest of failed * delivered - delivered messages * sent - delivered+failed (default events value) * pending - pending messages * total - all messages, i.e. sent+pending * abuse - spam complaints 
     * @param {String} opts.columns Array of columns to be specified in the report. These can differ based on any specified event type filter.   Possible column values are: * `message_id` - Unique message ID * from - From Address * to - Recipient Address * time_rcv - Date Received in RFC 2822 or UNIX epoch format * time_snt - Date Delivered in RFC 2822 or UNIX epoch format * channel - Name of a channel  Additional column values for message reports (hard_bounced, failed, delivered, total) include: * status - Status of delivery * code - SMTP Response Code * message - SMTP Response message * tries - Amount of re-tries (deferred states before final)  Additional column values for spam reports include:  * report_time - Date when an abuse complaint has been reported, RFC 2822 or UNIX epoch format * subject - Email Subject  Additional column values for pending reports include:  * status - Current email status  If not specified all relevant columns are included. 
     * @param {module:api/ReportsApi~v4ReportsPeriodicPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/StatusResponse}
     */
    v4ReportsPeriodicPost(frequency, reportTime, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'frequency' is set
      if (frequency === undefined || frequency === null) {
        throw new Error("Missing the required parameter 'frequency' when calling v4ReportsPeriodicPost");
      }
      // verify the required parameter 'reportTime' is set
      if (reportTime === undefined || reportTime === null) {
        throw new Error("Missing the required parameter 'reportTime' when calling v4ReportsPeriodicPost");
      }

      let pathParams = {
      };
      let queryParams = {
        'frequency': frequency,
        'report_time': reportTime,
        'channel': opts['channel'],
        'notify_method': opts['notifyMethod'],
        'notify_dest': opts['notifyDest'],
        'domain': opts['domain'],
        'rcpt_domain': opts['rcptDomain'],
        'events': opts['events'],
        'columns': opts['columns']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = StatusResponse;
      return this.apiClient.callApi(
        '/v4/reports/periodic', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4ReportsPeriodicReportIdDelete operation.
     * @callback module:api/ReportsApi~v4ReportsPeriodicReportIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param {module:model/StatusResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a Periodic Report
     * @param {String} reportId Id of a given report
     * @param {module:api/ReportsApi~v4ReportsPeriodicReportIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/StatusResponse}
     */
    v4ReportsPeriodicReportIdDelete(reportId, callback) {
      let postBody = null;
      // verify the required parameter 'reportId' is set
      if (reportId === undefined || reportId === null) {
        throw new Error("Missing the required parameter 'reportId' when calling v4ReportsPeriodicReportIdDelete");
      }

      let pathParams = {
        'report_id': reportId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = StatusResponse;
      return this.apiClient.callApi(
        '/v4/reports/periodic/{report_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4ReportsPeriodicReportIdPatch operation.
     * @callback module:api/ReportsApi~v4ReportsPeriodicReportIdPatchCallback
     * @param {String} error Error message, if any.
     * @param {module:model/StatusResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update Periodic Report
     * @param {String} reportId Id of the report to be updated
     * @param {module:model/String} frequency Report frequency – one of:  * daily - every day at a specified hour  * weekly  - Mondays at a specified hour  * monthly - first day of the month at a specified hour. 
     * @param {Number} reportTime The hour at which the report should be sent. Value values range from 0 to 23
     * @param {Object} opts Optional parameters
     * @param {String} opts.channel Name of channel (sender). If not specified all channels will be reported
     * @param {String} opts.events Filter by event type. Valid event are: * hard_bounced - just hard bounces * failed - all failed messages, i.e. hard_bounced + the rest of failed * delivered - delivered messages * sent - delivered+failed (default events value) * pending - pending messages * total - all messages, i.e. sent+pending * abuse - spam complaints  If not specified all events are included. 
     * @param {module:api/ReportsApi~v4ReportsPeriodicReportIdPatchCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/StatusResponse}
     */
    v4ReportsPeriodicReportIdPatch(reportId, frequency, reportTime, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'reportId' is set
      if (reportId === undefined || reportId === null) {
        throw new Error("Missing the required parameter 'reportId' when calling v4ReportsPeriodicReportIdPatch");
      }
      // verify the required parameter 'frequency' is set
      if (frequency === undefined || frequency === null) {
        throw new Error("Missing the required parameter 'frequency' when calling v4ReportsPeriodicReportIdPatch");
      }
      // verify the required parameter 'reportTime' is set
      if (reportTime === undefined || reportTime === null) {
        throw new Error("Missing the required parameter 'reportTime' when calling v4ReportsPeriodicReportIdPatch");
      }

      let pathParams = {
        'report_id': reportId
      };
      let queryParams = {
        'frequency': frequency,
        'report_time': reportTime,
        'channel': opts['channel'],
        'events': opts['events']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = StatusResponse;
      return this.apiClient.callApi(
        '/v4/reports/periodic/{report_id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the v4ReportsReportIdGet operation.
     * @callback module:api/ReportsApi~v4ReportsReportIdGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Report} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Report Details
     * @param {String} reportId ID of a given report
     * @param {module:api/ReportsApi~v4ReportsReportIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Report}
     */
    v4ReportsReportIdGet(reportId, callback) {
      let postBody = null;
      // verify the required parameter 'reportId' is set
      if (reportId === undefined || reportId === null) {
        throw new Error("Missing the required parameter 'reportId' when calling v4ReportsReportIdGet");
      }

      let pathParams = {
        'report_id': reportId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Report;
      return this.apiClient.callApi(
        '/v4/reports/{report_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
