/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import BadRequestSchema from '../model/BadRequestSchema';
import InvalidKey from '../model/InvalidKey';
import StatsResponse from '../model/StatsResponse';

/**
* Statistics service.
* @module api/StatisticsApi
* @version 4.0.0
*/
export default class StatisticsApi {

    /**
    * Constructs a new StatisticsApi. 
    * @alias module:api/StatisticsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the v4StatsDurationSliceSliceSpecifierGroupByGet operation.
     * @callback module:api/StatisticsApi~v4StatsDurationSliceSliceSpecifierGroupByGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/StatsResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Return event aggregates for the specified slices and duration. Slices can be chained.
     * **Get stats for a period**<br> Request:<br> *_/v4/stats/last_day*<br> *_/v4/stats?start=Tue%2C%2016%20Jan%2015%3A14%3A29%20%2B0000*<br> Response:<br> ``` {\"accepted\": 300, \"delivered\": 100, \"complained\": 0, \"failed\": 50, \"bounced\": 150, \"queued\": 0} ``` <br><br> **Get stats for a period, grouped by channel**<br> Request:<br> *_/v4/stats/last_day/channel*<br> Response:<br> ``` {\"channel1\": {\"accepted\": 30, \"delivered\": 10, \"complained\": 0, \"failed\": 5, \"bounced\": 15, \"queued\": 0}, \"channel2\": {\"accepted\": 0, \"delivered\": 0, \"complained\": 0, \"failed\": 0, \"bounced\": 0, \"queued\": 0}} ``` <br><br> **Get stats for specific sending domain and channel (sender) and period, grouped by ISP**<br> Request:<br> *_/v4/stats/last_day/channel/marketing/domain/smtp.com/rcpt_isp*<br> Response:<br> ``` {\"yahoo\": {\"accepted\": 30, \"delivered\": 10, \"complained\": 0, \"failed\": 5, \"bounced\": 15, \"queued\": 0}, \"google\": {\"accepted\": 0, \"delivered\": 0, \"complained\": 0, \"failed\": 0, \"bounced\": 0, \"queued\": 0}} ``` 
     * @param {String} start The starting time. Required if the `{duration}` path parameter is not specified. RFC 2822 or UNIX epoch format.
     * @param {module:model/String} duration A standardized shorthand for a known start/end bracket. Duration automatically supersedes start/end values provided as query string parameters. One of either the `{duration}` path parameter or the `start` query parameter must be specified.  <table>  <tr><th>Value</th><th>Start</th><th>End</th><th>Slicable</th></tr>  <tr><td>last_24hrs</td><td>84,400 seconds ago</td><td>Now</td><td>yes</td></tr>  <tr><td>last_30days</td><td>18,144,000 seconds ago</td><td>Now</td><td>yes</td></tr>  <tr><td>last_7days</td><td>604,800 seconds ago</td><td>Now</td><td>yes</td></tr>  <tr><td>last_day</td><td>00:00:00 of the previous day</td><td>23:59:59 of the previous day</td><td>yes</td></tr>  <tr><td>last_hour</td><td>00:00 of the previous hour</td><td>59:59 of the previous hour</td><td>yes</td></tr>  <tr><td>last_month or mtd</td><td>1st day 00:00:00 of previous month</td><td>23:59:59 last day of previous month</td><td>yes</td></tr>  <tr><td>last_week</td><td>Monday 00:00:00 of previous week</td><td>Sunday 23:59:59 of previous week</td><td>yes</td></tr>  <tr><td>this_day</td><td>00:00:00 of current day</td><td>Now</td><td>yes</td></tr>  <tr><td>this_hour</td><td>00:00 of current clock hour</td><td>Now</td><td>yes</td></tr>  <tr><td>this_month</td><td>1st day 00:00:00 of current month</td><td>Now</td><td>yes</td></tr>  <tr><td>this_week</td><td>Monday 00:00:00 of current week</td><td>Now</td><td>yes</td></tr>  <tr><td>last_year</td><td> Jan 1st 00:00:00 of previous year</td><td>Dec 31st 23:59:59 of previous year</td><td>no</td></tr>  <tr><td>this_year or ytd</td><td>Jan 1st  00:00:0 of current year</td><td>Now</td><td>no</td></tr>  <tr><td>total</td><td>Account creation date</td><td>Now</td><td>no</td></tr>  </table> 
     * @param {module:model/String} slice A reducing method which can be applied to the requested duration. A final slice without an optional slice specifier will define a grouping.  Possible Values:  * `channel`: (optional) A given account's sender  * `domain`: (optional) Sending domain  * `rcpt_domain`: (optional) Recieving domain  * `rcpt_isp`: (optional) Receiving ISP     Slices can be chained in a meaningful way – for example:   ```   /last_month/channel/marketing/domain/smtp.com/rcpt_domain?event=complained   ``` would produce an aggregate of complaints for a current account’s channel (sender) called “marketing” which were:   * sent from the registered email domain “smtp.com”, and    * are grouped by receiving domains       The response would look something like:   ```   {“google.com”: {“complained”: 5}, “yahoo.com”: {“complained”:1}, “aol.com”: {“complained”:1}}   ``` 
     * @param {String} sliceSpecifier slice value (smtp.com, sender1)
     * @param {module:model/String} groupBy Define a grouping:  * `channel` - optionally to be followed by a channel ID or name specifier  * `domain`  - optionally to be followed by a registered domain name  * `rcpt_domain` - optionally to be followed by a registered domain name  * `rcpt_isp` - optionally to be followed by a registered domain name 
     * @param {Number} limit Maximum number of items to return.
     * @param {Number} offset Number of items to skip before returning the results.
     * @param {Object} opts Optional parameters
     * @param {String} opts.end The ending time. If not specified, defaults to now. RFC 2822 or UNIX epoch format.
     * @param {module:model/String} opts.event Array of any event names for which stats has been requested.
     * @param {module:api/StatisticsApi~v4StatsDurationSliceSliceSpecifierGroupByGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/StatsResponse}
     */
    v4StatsDurationSliceSliceSpecifierGroupByGet(start, duration, slice, sliceSpecifier, groupBy, limit, offset, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'start' is set
      if (start === undefined || start === null) {
        throw new Error("Missing the required parameter 'start' when calling v4StatsDurationSliceSliceSpecifierGroupByGet");
      }
      // verify the required parameter 'duration' is set
      if (duration === undefined || duration === null) {
        throw new Error("Missing the required parameter 'duration' when calling v4StatsDurationSliceSliceSpecifierGroupByGet");
      }
      // verify the required parameter 'slice' is set
      if (slice === undefined || slice === null) {
        throw new Error("Missing the required parameter 'slice' when calling v4StatsDurationSliceSliceSpecifierGroupByGet");
      }
      // verify the required parameter 'sliceSpecifier' is set
      if (sliceSpecifier === undefined || sliceSpecifier === null) {
        throw new Error("Missing the required parameter 'sliceSpecifier' when calling v4StatsDurationSliceSliceSpecifierGroupByGet");
      }
      // verify the required parameter 'groupBy' is set
      if (groupBy === undefined || groupBy === null) {
        throw new Error("Missing the required parameter 'groupBy' when calling v4StatsDurationSliceSliceSpecifierGroupByGet");
      }
      // verify the required parameter 'limit' is set
      if (limit === undefined || limit === null) {
        throw new Error("Missing the required parameter 'limit' when calling v4StatsDurationSliceSliceSpecifierGroupByGet");
      }
      // verify the required parameter 'offset' is set
      if (offset === undefined || offset === null) {
        throw new Error("Missing the required parameter 'offset' when calling v4StatsDurationSliceSliceSpecifierGroupByGet");
      }

      let pathParams = {
        'duration': duration,
        'slice': slice,
        'slice_specifier': sliceSpecifier,
        'group_by': groupBy
      };
      let queryParams = {
        'start': start,
        'end': opts['end'],
        'event': opts['event'],
        'limit': limit,
        'offset': offset
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['apiID', 'apiKey', 'basicAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = StatsResponse;
      return this.apiClient.callApi(
        '/v4/stats/{duration}/{slice}/{slice_specifier}/{group_by}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
