/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SmtpPublicApiOverview);
  }
}(this, function(expect, SmtpPublicApiOverview) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SmtpPublicApiOverview.GetAlertResponseDataItems();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetAlertResponseDataItems', function() {
    it('should create an instance of GetAlertResponseDataItems', function() {
      // uncomment below and update the code to test GetAlertResponseDataItems
      //var instane = new SmtpPublicApiOverview.GetAlertResponseDataItems();
      //expect(instance).to.be.a(SmtpPublicApiOverview.GetAlertResponseDataItems);
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instane = new SmtpPublicApiOverview.GetAlertResponseDataItems();
      //expect(instance).to.be();
    });

    it('should have the property threshold (base name: "threshold")', function() {
      // uncomment below and update the code to test the property threshold
      //var instane = new SmtpPublicApiOverview.GetAlertResponseDataItems();
      //expect(instance).to.be();
    });

    it('should have the property alertId (base name: "alert_id")', function() {
      // uncomment below and update the code to test the property alertId
      //var instane = new SmtpPublicApiOverview.GetAlertResponseDataItems();
      //expect(instance).to.be();
    });

  });

}));
