/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SmtpComApi);
  }
}(this, function(expect, SmtpComApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SmtpComApi.MessagesResponseDataItems();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MessagesResponseDataItems', function() {
    it('should create an instance of MessagesResponseDataItems', function() {
      // uncomment below and update the code to test MessagesResponseDataItems
      //var instane = new SmtpComApi.MessagesResponseDataItems();
      //expect(instance).to.be.a(SmtpComApi.MessagesResponseDataItems);
    });

    it('should have the property msgId (base name: "msg_id")', function() {
      // uncomment below and update the code to test the property msgId
      //var instane = new SmtpComApi.MessagesResponseDataItems();
      //expect(instance).to.be();
    });

    it('should have the property msgTime (base name: "msg_time")', function() {
      // uncomment below and update the code to test the property msgTime
      //var instane = new SmtpComApi.MessagesResponseDataItems();
      //expect(instance).to.be();
    });

    it('should have the property channel (base name: "channel")', function() {
      // uncomment below and update the code to test the property channel
      //var instane = new SmtpComApi.MessagesResponseDataItems();
      //expect(instance).to.be();
    });

    it('should have the property smtpVars (base name: "smtp_vars")', function() {
      // uncomment below and update the code to test the property smtpVars
      //var instane = new SmtpComApi.MessagesResponseDataItems();
      //expect(instance).to.be();
    });

    it('should have the property msgData (base name: "msg_data")', function() {
      // uncomment below and update the code to test the property msgData
      //var instane = new SmtpComApi.MessagesResponseDataItems();
      //expect(instance).to.be();
    });

    it('should have the property details (base name: "details")', function() {
      // uncomment below and update the code to test the property details
      //var instane = new SmtpComApi.MessagesResponseDataItems();
      //expect(instance).to.be();
    });

    it('should have the property opens (base name: "opens")', function() {
      // uncomment below and update the code to test the property opens
      //var instane = new SmtpComApi.MessagesResponseDataItems();
      //expect(instance).to.be();
    });

    it('should have the property clicks (base name: "clicks")', function() {
      // uncomment below and update the code to test the property clicks
      //var instane = new SmtpComApi.MessagesResponseDataItems();
      //expect(instance).to.be();
    });

    it('should have the property abuse (base name: "abuse")', function() {
      // uncomment below and update the code to test the property abuse
      //var instane = new SmtpComApi.MessagesResponseDataItems();
      //expect(instance).to.be();
    });

    it('should have the property unsubs (base name: "unsubs")', function() {
      // uncomment below and update the code to test the property unsubs
      //var instane = new SmtpComApi.MessagesResponseDataItems();
      //expect(instance).to.be();
    });

  });

}));
