/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SmtpPublicApiOverview);
  }
}(this, function(expect, SmtpPublicApiOverview) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SmtpPublicApiOverview.Report();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Report', function() {
    it('should create an instance of Report', function() {
      // uncomment below and update the code to test Report
      //var instane = new SmtpPublicApiOverview.Report();
      //expect(instance).to.be.a(SmtpPublicApiOverview.Report);
    });

    it('should have the property frequency (base name: "frequency")', function() {
      // uncomment below and update the code to test the property frequency
      //var instane = new SmtpPublicApiOverview.Report();
      //expect(instance).to.be();
    });

    it('should have the property reportId (base name: "report_id")', function() {
      // uncomment below and update the code to test the property reportId
      //var instane = new SmtpPublicApiOverview.Report();
      //expect(instance).to.be();
    });

    it('should have the property events (base name: "events")', function() {
      // uncomment below and update the code to test the property events
      //var instane = new SmtpPublicApiOverview.Report();
      //expect(instance).to.be();
    });

    it('should have the property channel (base name: "channel")', function() {
      // uncomment below and update the code to test the property channel
      //var instane = new SmtpPublicApiOverview.Report();
      //expect(instance).to.be();
    });

    it('should have the property reportTime (base name: "report_time")', function() {
      // uncomment below and update the code to test the property reportTime
      //var instane = new SmtpPublicApiOverview.Report();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instane = new SmtpPublicApiOverview.Report();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new SmtpPublicApiOverview.Report();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instane = new SmtpPublicApiOverview.Report();
      //expect(instance).to.be();
    });

    it('should have the property timeReq (base name: "time_req")', function() {
      // uncomment below and update the code to test the property timeReq
      //var instane = new SmtpPublicApiOverview.Report();
      //expect(instance).to.be();
    });

    it('should have the property progress (base name: "progress")', function() {
      // uncomment below and update the code to test the property progress
      //var instane = new SmtpPublicApiOverview.Report();
      //expect(instance).to.be();
    });

  });

}));
