/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SmtpComApi);
  }
}(this, function(expect, SmtpComApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SmtpComApi.StatsResponseDataItems();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StatsResponseDataItems', function() {
    it('should create an instance of StatsResponseDataItems', function() {
      // uncomment below and update the code to test StatsResponseDataItems
      //var instane = new SmtpComApi.StatsResponseDataItems();
      //expect(instance).to.be.a(SmtpComApi.StatsResponseDataItems);
    });

    it('should have the property accepted (base name: "accepted")', function() {
      // uncomment below and update the code to test the property accepted
      //var instane = new SmtpComApi.StatsResponseDataItems();
      //expect(instance).to.be();
    });

    it('should have the property complained (base name: "complained")', function() {
      // uncomment below and update the code to test the property complained
      //var instane = new SmtpComApi.StatsResponseDataItems();
      //expect(instance).to.be();
    });

    it('should have the property delivered (base name: "delivered")', function() {
      // uncomment below and update the code to test the property delivered
      //var instane = new SmtpComApi.StatsResponseDataItems();
      //expect(instance).to.be();
    });

    it('should have the property clicked (base name: "clicked")', function() {
      // uncomment below and update the code to test the property clicked
      //var instane = new SmtpComApi.StatsResponseDataItems();
      //expect(instance).to.be();
    });

    it('should have the property opened (base name: "opened")', function() {
      // uncomment below and update the code to test the property opened
      //var instane = new SmtpComApi.StatsResponseDataItems();
      //expect(instance).to.be();
    });

    it('should have the property failed (base name: "failed")', function() {
      // uncomment below and update the code to test the property failed
      //var instane = new SmtpComApi.StatsResponseDataItems();
      //expect(instance).to.be();
    });

    it('should have the property unsubscribed (base name: "unsubscribed")', function() {
      // uncomment below and update the code to test the property unsubscribed
      //var instane = new SmtpComApi.StatsResponseDataItems();
      //expect(instance).to.be();
    });

    it('should have the property queued (base name: "queued")', function() {
      // uncomment below and update the code to test the property queued
      //var instane = new SmtpComApi.StatsResponseDataItems();
      //expect(instance).to.be();
    });

  });

}));
