/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SmtpPublicApiOverview);
  }
}(this, function(expect, SmtpPublicApiOverview) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SmtpPublicApiOverview.V4MessagesBody();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('V4MessagesBody', function() {
    it('should create an instance of V4MessagesBody', function() {
      // uncomment below and update the code to test V4MessagesBody
      //var instane = new SmtpPublicApiOverview.V4MessagesBody();
      //expect(instance).to.be.a(SmtpPublicApiOverview.V4MessagesBody);
    });

    it('should have the property parts (base name: "parts")', function() {
      // uncomment below and update the code to test the property parts
      //var instane = new SmtpPublicApiOverview.V4MessagesBody();
      //expect(instance).to.be();
    });

    it('should have the property attachments (base name: "attachments")', function() {
      // uncomment below and update the code to test the property attachments
      //var instane = new SmtpPublicApiOverview.V4MessagesBody();
      //expect(instance).to.be();
    });

  });

}));
