/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import APIKey from './model/APIKey';
import Account from './model/Account';
import AccountData from './model/AccountData';
import AccountDataAddress from './model/AccountDataAddress';
import BadRequestSchema from './model/BadRequestSchema';
import BadRequestSchemaData from './model/BadRequestSchemaData';
import Channel from './model/Channel';
import ChannelData from './model/ChannelData';
import Channels from './model/Channels';
import ChannelsData from './model/ChannelsData';
import ChannelsDataItems from './model/ChannelsDataItems';
import CreateCallbackResponse from './model/CreateCallbackResponse';
import CreateDkimKey from './model/CreateDkimKey';
import CreateDkimKeyData from './model/CreateDkimKeyData';
import CreateDomainResponse from './model/CreateDomainResponse';
import CreateDomainResponseData from './model/CreateDomainResponseData';
import DurationValue from './model/DurationValue';
import GetAlertDetails from './model/GetAlertDetails';
import GetAlertDetailsData from './model/GetAlertDetailsData';
import GetAlertResponse from './model/GetAlertResponse';
import GetAlertResponseData from './model/GetAlertResponseData';
import GetAlertResponseDataItems from './model/GetAlertResponseDataItems';
import GetApiKeys from './model/GetApiKeys';
import GetApiKeysData from './model/GetApiKeysData';
import GetApiKeysDataItems from './model/GetApiKeysDataItems';
import GetCallbackDetails from './model/GetCallbackDetails';
import GetCallbackDetailsData from './model/GetCallbackDetailsData';
import GetCallbackLogs from './model/GetCallbackLogs';
import GetCallbackLogsData from './model/GetCallbackLogsData';
import GetCallbackLogsDataItems from './model/GetCallbackLogsDataItems';
import GetCallbackResponse from './model/GetCallbackResponse';
import GetCallbackResponseData from './model/GetCallbackResponseData';
import GetCallbackResponseDataItems from './model/GetCallbackResponseDataItems';
import GetDomainDetails from './model/GetDomainDetails';
import GetDomainDetailsData from './model/GetDomainDetailsData';
import GetDomainDetailsResponse from './model/GetDomainDetailsResponse';
import GetDomainDetailsResponseData from './model/GetDomainDetailsResponseData';
import GetDomainsResponse from './model/GetDomainsResponse';
import GetDomainsResponseData from './model/GetDomainsResponseData';
import GetDomainsResponseDataItems from './model/GetDomainsResponseDataItems';
import InlineObject from './model/InlineObject';
import InlineObject1 from './model/InlineObject1';
import InvalidKey from './model/InvalidKey';
import InvalidKeyData from './model/InvalidKeyData';
import InvalidKeyDataErrors from './model/InvalidKeyDataErrors';
import MessagesResponse from './model/MessagesResponse';
import MessagesResponseData from './model/MessagesResponseData';
import MessagesResponseDataAbuse from './model/MessagesResponseDataAbuse';
import MessagesResponseDataAbuseComplaints from './model/MessagesResponseDataAbuseComplaints';
import MessagesResponseDataClicks from './model/MessagesResponseDataClicks';
import MessagesResponseDataClicksItems from './model/MessagesResponseDataClicksItems';
import MessagesResponseDataDetails from './model/MessagesResponseDataDetails';
import MessagesResponseDataDetailsDelivery from './model/MessagesResponseDataDetailsDelivery';
import MessagesResponseDataItems from './model/MessagesResponseDataItems';
import MessagesResponseDataMsgData from './model/MessagesResponseDataMsgData';
import MessagesResponseDataOpens from './model/MessagesResponseDataOpens';
import MessagesResponseDataOpensItems from './model/MessagesResponseDataOpensItems';
import MessagesResponseDataUnsubs from './model/MessagesResponseDataUnsubs';
import MessagesResponseDataUnsubsItems from './model/MessagesResponseDataUnsubsItems';
import MimeResponse from './model/MimeResponse';
import PostMessageResponse from './model/PostMessageResponse';
import PostMessageResponseData from './model/PostMessageResponseData';
import Report from './model/Report';
import Reports from './model/Reports';
import ReportsData from './model/ReportsData';
import ReportsDataOndemand from './model/ReportsDataOndemand';
import ReportsDataPeriodic from './model/ReportsDataPeriodic';
import SliceValue from './model/SliceValue';
import StatsResponse from './model/StatsResponse';
import StatsResponseData from './model/StatsResponseData';
import StatsResponseDataItems from './model/StatsResponseDataItems';
import StatusResponse from './model/StatusResponse';
import UpdateAccountResponse from './model/UpdateAccountResponse';
import UpdateAccountResponseData from './model/UpdateAccountResponseData';
import V4MessagesBody from './model/V4MessagesBody';
import V4MessagesBodyAttachments from './model/V4MessagesBodyAttachments';
import V4MessagesBodyParts from './model/V4MessagesBodyParts';
import V4MessagesMimeRecipients from './model/V4MessagesMimeRecipients';
import V4MessagesOriginator from './model/V4MessagesOriginator';
import V4MessagesRecipients from './model/V4MessagesRecipients';
import V4MessagesRecipientsTo from './model/V4MessagesRecipientsTo';
import APIKeysApi from './api/APIKeysApi';
import AccountApi from './api/AccountApi';
import AlertsApi from './api/AlertsApi';
import CallbacksApi from './api/CallbacksApi';
import ChannelsApi from './api/ChannelsApi';
import DKIMsApi from './api/DKIMsApi';
import MessagesApi from './api/MessagesApi';
import ReportsApi from './api/ReportsApi';
import StatisticsApi from './api/StatisticsApi';


/**
* SMTP_com_Public_API_v4.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var SmtpPublicApiOverview = require('index'); // See note below*.
* var xxxSvc = new SmtpPublicApiOverview.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new SmtpPublicApiOverview.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new SmtpPublicApiOverview.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new SmtpPublicApiOverview.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 4.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The APIKey model constructor.
     * @property {module:model/APIKey}
     */
    APIKey,

    /**
     * The Account model constructor.
     * @property {module:model/Account}
     */
    Account,

    /**
     * The AccountData model constructor.
     * @property {module:model/AccountData}
     */
    AccountData,

    /**
     * The AccountDataAddress model constructor.
     * @property {module:model/AccountDataAddress}
     */
    AccountDataAddress,

    /**
     * The BadRequestSchema model constructor.
     * @property {module:model/BadRequestSchema}
     */
    BadRequestSchema,

    /**
     * The BadRequestSchemaData model constructor.
     * @property {module:model/BadRequestSchemaData}
     */
    BadRequestSchemaData,

    /**
     * The Channel model constructor.
     * @property {module:model/Channel}
     */
    Channel,

    /**
     * The ChannelData model constructor.
     * @property {module:model/ChannelData}
     */
    ChannelData,

    /**
     * The Channels model constructor.
     * @property {module:model/Channels}
     */
    Channels,

    /**
     * The ChannelsData model constructor.
     * @property {module:model/ChannelsData}
     */
    ChannelsData,

    /**
     * The ChannelsDataItems model constructor.
     * @property {module:model/ChannelsDataItems}
     */
    ChannelsDataItems,

    /**
     * The CreateCallbackResponse model constructor.
     * @property {module:model/CreateCallbackResponse}
     */
    CreateCallbackResponse,

    /**
     * The CreateDkimKey model constructor.
     * @property {module:model/CreateDkimKey}
     */
    CreateDkimKey,

    /**
     * The CreateDkimKeyData model constructor.
     * @property {module:model/CreateDkimKeyData}
     */
    CreateDkimKeyData,

    /**
     * The CreateDomainResponse model constructor.
     * @property {module:model/CreateDomainResponse}
     */
    CreateDomainResponse,

    /**
     * The CreateDomainResponseData model constructor.
     * @property {module:model/CreateDomainResponseData}
     */
    CreateDomainResponseData,

    /**
     * The DurationValue model constructor.
     * @property {module:model/DurationValue}
     */
    DurationValue,

    /**
     * The GetAlertDetails model constructor.
     * @property {module:model/GetAlertDetails}
     */
    GetAlertDetails,

    /**
     * The GetAlertDetailsData model constructor.
     * @property {module:model/GetAlertDetailsData}
     */
    GetAlertDetailsData,

    /**
     * The GetAlertResponse model constructor.
     * @property {module:model/GetAlertResponse}
     */
    GetAlertResponse,

    /**
     * The GetAlertResponseData model constructor.
     * @property {module:model/GetAlertResponseData}
     */
    GetAlertResponseData,

    /**
     * The GetAlertResponseDataItems model constructor.
     * @property {module:model/GetAlertResponseDataItems}
     */
    GetAlertResponseDataItems,

    /**
     * The GetApiKeys model constructor.
     * @property {module:model/GetApiKeys}
     */
    GetApiKeys,

    /**
     * The GetApiKeysData model constructor.
     * @property {module:model/GetApiKeysData}
     */
    GetApiKeysData,

    /**
     * The GetApiKeysDataItems model constructor.
     * @property {module:model/GetApiKeysDataItems}
     */
    GetApiKeysDataItems,

    /**
     * The GetCallbackDetails model constructor.
     * @property {module:model/GetCallbackDetails}
     */
    GetCallbackDetails,

    /**
     * The GetCallbackDetailsData model constructor.
     * @property {module:model/GetCallbackDetailsData}
     */
    GetCallbackDetailsData,

    /**
     * The GetCallbackLogs model constructor.
     * @property {module:model/GetCallbackLogs}
     */
    GetCallbackLogs,

    /**
     * The GetCallbackLogsData model constructor.
     * @property {module:model/GetCallbackLogsData}
     */
    GetCallbackLogsData,

    /**
     * The GetCallbackLogsDataItems model constructor.
     * @property {module:model/GetCallbackLogsDataItems}
     */
    GetCallbackLogsDataItems,

    /**
     * The GetCallbackResponse model constructor.
     * @property {module:model/GetCallbackResponse}
     */
    GetCallbackResponse,

    /**
     * The GetCallbackResponseData model constructor.
     * @property {module:model/GetCallbackResponseData}
     */
    GetCallbackResponseData,

    /**
     * The GetCallbackResponseDataItems model constructor.
     * @property {module:model/GetCallbackResponseDataItems}
     */
    GetCallbackResponseDataItems,

    /**
     * The GetDomainDetails model constructor.
     * @property {module:model/GetDomainDetails}
     */
    GetDomainDetails,

    /**
     * The GetDomainDetailsData model constructor.
     * @property {module:model/GetDomainDetailsData}
     */
    GetDomainDetailsData,

    /**
     * The GetDomainDetailsResponse model constructor.
     * @property {module:model/GetDomainDetailsResponse}
     */
    GetDomainDetailsResponse,

    /**
     * The GetDomainDetailsResponseData model constructor.
     * @property {module:model/GetDomainDetailsResponseData}
     */
    GetDomainDetailsResponseData,

    /**
     * The GetDomainsResponse model constructor.
     * @property {module:model/GetDomainsResponse}
     */
    GetDomainsResponse,

    /**
     * The GetDomainsResponseData model constructor.
     * @property {module:model/GetDomainsResponseData}
     */
    GetDomainsResponseData,

    /**
     * The GetDomainsResponseDataItems model constructor.
     * @property {module:model/GetDomainsResponseDataItems}
     */
    GetDomainsResponseDataItems,

    /**
     * The InlineObject model constructor.
     * @property {module:model/InlineObject}
     */
    InlineObject,

    /**
     * The InlineObject1 model constructor.
     * @property {module:model/InlineObject1}
     */
    InlineObject1,

    /**
     * The InvalidKey model constructor.
     * @property {module:model/InvalidKey}
     */
    InvalidKey,

    /**
     * The InvalidKeyData model constructor.
     * @property {module:model/InvalidKeyData}
     */
    InvalidKeyData,

    /**
     * The InvalidKeyDataErrors model constructor.
     * @property {module:model/InvalidKeyDataErrors}
     */
    InvalidKeyDataErrors,

    /**
     * The MessagesResponse model constructor.
     * @property {module:model/MessagesResponse}
     */
    MessagesResponse,

    /**
     * The MessagesResponseData model constructor.
     * @property {module:model/MessagesResponseData}
     */
    MessagesResponseData,

    /**
     * The MessagesResponseDataAbuse model constructor.
     * @property {module:model/MessagesResponseDataAbuse}
     */
    MessagesResponseDataAbuse,

    /**
     * The MessagesResponseDataAbuseComplaints model constructor.
     * @property {module:model/MessagesResponseDataAbuseComplaints}
     */
    MessagesResponseDataAbuseComplaints,

    /**
     * The MessagesResponseDataClicks model constructor.
     * @property {module:model/MessagesResponseDataClicks}
     */
    MessagesResponseDataClicks,

    /**
     * The MessagesResponseDataClicksItems model constructor.
     * @property {module:model/MessagesResponseDataClicksItems}
     */
    MessagesResponseDataClicksItems,

    /**
     * The MessagesResponseDataDetails model constructor.
     * @property {module:model/MessagesResponseDataDetails}
     */
    MessagesResponseDataDetails,

    /**
     * The MessagesResponseDataDetailsDelivery model constructor.
     * @property {module:model/MessagesResponseDataDetailsDelivery}
     */
    MessagesResponseDataDetailsDelivery,

    /**
     * The MessagesResponseDataItems model constructor.
     * @property {module:model/MessagesResponseDataItems}
     */
    MessagesResponseDataItems,

    /**
     * The MessagesResponseDataMsgData model constructor.
     * @property {module:model/MessagesResponseDataMsgData}
     */
    MessagesResponseDataMsgData,

    /**
     * The MessagesResponseDataOpens model constructor.
     * @property {module:model/MessagesResponseDataOpens}
     */
    MessagesResponseDataOpens,

    /**
     * The MessagesResponseDataOpensItems model constructor.
     * @property {module:model/MessagesResponseDataOpensItems}
     */
    MessagesResponseDataOpensItems,

    /**
     * The MessagesResponseDataUnsubs model constructor.
     * @property {module:model/MessagesResponseDataUnsubs}
     */
    MessagesResponseDataUnsubs,

    /**
     * The MessagesResponseDataUnsubsItems model constructor.
     * @property {module:model/MessagesResponseDataUnsubsItems}
     */
    MessagesResponseDataUnsubsItems,

    /**
     * The MimeResponse model constructor.
     * @property {module:model/MimeResponse}
     */
    MimeResponse,

    /**
     * The PostMessageResponse model constructor.
     * @property {module:model/PostMessageResponse}
     */
    PostMessageResponse,

    /**
     * The PostMessageResponseData model constructor.
     * @property {module:model/PostMessageResponseData}
     */
    PostMessageResponseData,

    /**
     * The Report model constructor.
     * @property {module:model/Report}
     */
    Report,

    /**
     * The Reports model constructor.
     * @property {module:model/Reports}
     */
    Reports,

    /**
     * The ReportsData model constructor.
     * @property {module:model/ReportsData}
     */
    ReportsData,

    /**
     * The ReportsDataOndemand model constructor.
     * @property {module:model/ReportsDataOndemand}
     */
    ReportsDataOndemand,

    /**
     * The ReportsDataPeriodic model constructor.
     * @property {module:model/ReportsDataPeriodic}
     */
    ReportsDataPeriodic,

    /**
     * The SliceValue model constructor.
     * @property {module:model/SliceValue}
     */
    SliceValue,

    /**
     * The StatsResponse model constructor.
     * @property {module:model/StatsResponse}
     */
    StatsResponse,

    /**
     * The StatsResponseData model constructor.
     * @property {module:model/StatsResponseData}
     */
    StatsResponseData,

    /**
     * The StatsResponseDataItems model constructor.
     * @property {module:model/StatsResponseDataItems}
     */
    StatsResponseDataItems,

    /**
     * The StatusResponse model constructor.
     * @property {module:model/StatusResponse}
     */
    StatusResponse,

    /**
     * The UpdateAccountResponse model constructor.
     * @property {module:model/UpdateAccountResponse}
     */
    UpdateAccountResponse,

    /**
     * The UpdateAccountResponseData model constructor.
     * @property {module:model/UpdateAccountResponseData}
     */
    UpdateAccountResponseData,

    /**
     * The V4MessagesBody model constructor.
     * @property {module:model/V4MessagesBody}
     */
    V4MessagesBody,

    /**
     * The V4MessagesBodyAttachments model constructor.
     * @property {module:model/V4MessagesBodyAttachments}
     */
    V4MessagesBodyAttachments,

    /**
     * The V4MessagesBodyParts model constructor.
     * @property {module:model/V4MessagesBodyParts}
     */
    V4MessagesBodyParts,

    /**
     * The V4MessagesMimeRecipients model constructor.
     * @property {module:model/V4MessagesMimeRecipients}
     */
    V4MessagesMimeRecipients,

    /**
     * The V4MessagesOriginator model constructor.
     * @property {module:model/V4MessagesOriginator}
     */
    V4MessagesOriginator,

    /**
     * The V4MessagesRecipients model constructor.
     * @property {module:model/V4MessagesRecipients}
     */
    V4MessagesRecipients,

    /**
     * The V4MessagesRecipientsTo model constructor.
     * @property {module:model/V4MessagesRecipientsTo}
     */
    V4MessagesRecipientsTo,

    /**
    * The APIKeysApi service constructor.
    * @property {module:api/APIKeysApi}
    */
    APIKeysApi,

    /**
    * The AccountApi service constructor.
    * @property {module:api/AccountApi}
    */
    AccountApi,

    /**
    * The AlertsApi service constructor.
    * @property {module:api/AlertsApi}
    */
    AlertsApi,

    /**
    * The CallbacksApi service constructor.
    * @property {module:api/CallbacksApi}
    */
    CallbacksApi,

    /**
    * The ChannelsApi service constructor.
    * @property {module:api/ChannelsApi}
    */
    ChannelsApi,

    /**
    * The DKIMsApi service constructor.
    * @property {module:api/DKIMsApi}
    */
    DKIMsApi,

    /**
    * The MessagesApi service constructor.
    * @property {module:api/MessagesApi}
    */
    MessagesApi,

    /**
    * The ReportsApi service constructor.
    * @property {module:api/ReportsApi}
    */
    ReportsApi,

    /**
    * The StatisticsApi service constructor.
    * @property {module:api/StatisticsApi}
    */
    StatisticsApi
};
