/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SmtpPublicApiOverview);
  }
}(this, function(expect, SmtpPublicApiOverview) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SmtpPublicApiOverview.AlertsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AlertsApi', function() {
    describe('v4AlertsAlertIdDelete', function() {
      it('should call v4AlertsAlertIdDelete successfully', function(done) {
        //uncomment below and update the code to test v4AlertsAlertIdDelete
        //instance.v4AlertsAlertIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4AlertsAlertIdGet', function() {
      it('should call v4AlertsAlertIdGet successfully', function(done) {
        //uncomment below and update the code to test v4AlertsAlertIdGet
        //instance.v4AlertsAlertIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4AlertsAlertIdPatch', function() {
      it('should call v4AlertsAlertIdPatch successfully', function(done) {
        //uncomment below and update the code to test v4AlertsAlertIdPatch
        //instance.v4AlertsAlertIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4AlertsGet', function() {
      it('should call v4AlertsGet successfully', function(done) {
        //uncomment below and update the code to test v4AlertsGet
        //instance.v4AlertsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4AlertsPost', function() {
      it('should call v4AlertsPost successfully', function(done) {
        //uncomment below and update the code to test v4AlertsPost
        //instance.v4AlertsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
