/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SmtpComApi);
  }
}(this, function(expect, SmtpComApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SmtpComApi.APIKeysApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('APIKeysApi', function() {
    describe('getAPIKey', function() {
      it('should call getAPIKey successfully', function(done) {
        //uncomment below and update the code to test getAPIKey
        //instance.getAPIKey(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4ApiKeysApiKeyDelete', function() {
      it('should call v4ApiKeysApiKeyDelete successfully', function(done) {
        //uncomment below and update the code to test v4ApiKeysApiKeyDelete
        //instance.v4ApiKeysApiKeyDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4ApiKeysApiKeyPatch', function() {
      it('should call v4ApiKeysApiKeyPatch successfully', function(done) {
        //uncomment below and update the code to test v4ApiKeysApiKeyPatch
        //instance.v4ApiKeysApiKeyPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4ApiKeysGet', function() {
      it('should call v4ApiKeysGet successfully', function(done) {
        //uncomment below and update the code to test v4ApiKeysGet
        //instance.v4ApiKeysGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4ApiKeysPost', function() {
      it('should call v4ApiKeysPost successfully', function(done) {
        //uncomment below and update the code to test v4ApiKeysPost
        //instance.v4ApiKeysPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
