/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SmtpComApi);
  }
}(this, function(expect, SmtpComApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SmtpComApi.CallbacksApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CallbacksApi', function() {
    describe('v4CallbacksDelete', function() {
      it('should call v4CallbacksDelete successfully', function(done) {
        //uncomment below and update the code to test v4CallbacksDelete
        //instance.v4CallbacksDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4CallbacksEventDelete', function() {
      it('should call v4CallbacksEventDelete successfully', function(done) {
        //uncomment below and update the code to test v4CallbacksEventDelete
        //instance.v4CallbacksEventDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4CallbacksEventGet', function() {
      it('should call v4CallbacksEventGet successfully', function(done) {
        //uncomment below and update the code to test v4CallbacksEventGet
        //instance.v4CallbacksEventGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4CallbacksEventPatch', function() {
      it('should call v4CallbacksEventPatch successfully', function(done) {
        //uncomment below and update the code to test v4CallbacksEventPatch
        //instance.v4CallbacksEventPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4CallbacksEventPost', function() {
      it('should call v4CallbacksEventPost successfully', function(done) {
        //uncomment below and update the code to test v4CallbacksEventPost
        //instance.v4CallbacksEventPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4CallbacksGet', function() {
      it('should call v4CallbacksGet successfully', function(done) {
        //uncomment below and update the code to test v4CallbacksGet
        //instance.v4CallbacksGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4CallbacksLogGet', function() {
      it('should call v4CallbacksLogGet successfully', function(done) {
        //uncomment below and update the code to test v4CallbacksLogGet
        //instance.v4CallbacksLogGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
