/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SmtpComApi);
  }
}(this, function(expect, SmtpComApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SmtpComApi.ChannelsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ChannelsApi', function() {
    describe('getSender', function() {
      it('should call getSender successfully', function(done) {
        //uncomment below and update the code to test getSender
        //instance.getSender(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4ChannelsGet', function() {
      it('should call v4ChannelsGet successfully', function(done) {
        //uncomment below and update the code to test v4ChannelsGet
        //instance.v4ChannelsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4ChannelsNameDelete', function() {
      it('should call v4ChannelsNameDelete successfully', function(done) {
        //uncomment below and update the code to test v4ChannelsNameDelete
        //instance.v4ChannelsNameDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4ChannelsNamePatch', function() {
      it('should call v4ChannelsNamePatch successfully', function(done) {
        //uncomment below and update the code to test v4ChannelsNamePatch
        //instance.v4ChannelsNamePatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4ChannelsPost', function() {
      it('should call v4ChannelsPost successfully', function(done) {
        //uncomment below and update the code to test v4ChannelsPost
        //instance.v4ChannelsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
