/**
 * SMTP.com API
 * SMTP.com API V4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SmtpComApi);
  }
}(this, function(expect, SmtpComApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SmtpComApi.DKIMsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DKIMsApi', function() {
    describe('v4DomainsDomainNameDelete', function() {
      it('should call v4DomainsDomainNameDelete successfully', function(done) {
        //uncomment below and update the code to test v4DomainsDomainNameDelete
        //instance.v4DomainsDomainNameDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4DomainsDomainNameDkimKeysDelete', function() {
      it('should call v4DomainsDomainNameDkimKeysDelete successfully', function(done) {
        //uncomment below and update the code to test v4DomainsDomainNameDkimKeysDelete
        //instance.v4DomainsDomainNameDkimKeysDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4DomainsDomainNameDkimKeysGet', function() {
      it('should call v4DomainsDomainNameDkimKeysGet successfully', function(done) {
        //uncomment below and update the code to test v4DomainsDomainNameDkimKeysGet
        //instance.v4DomainsDomainNameDkimKeysGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4DomainsDomainNameDkimKeysPatch', function() {
      it('should call v4DomainsDomainNameDkimKeysPatch successfully', function(done) {
        //uncomment below and update the code to test v4DomainsDomainNameDkimKeysPatch
        //instance.v4DomainsDomainNameDkimKeysPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4DomainsDomainNameDkimKeysPost', function() {
      it('should call v4DomainsDomainNameDkimKeysPost successfully', function(done) {
        //uncomment below and update the code to test v4DomainsDomainNameDkimKeysPost
        //instance.v4DomainsDomainNameDkimKeysPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4DomainsDomainNameGet', function() {
      it('should call v4DomainsDomainNameGet successfully', function(done) {
        //uncomment below and update the code to test v4DomainsDomainNameGet
        //instance.v4DomainsDomainNameGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4DomainsDomainNamePatch', function() {
      it('should call v4DomainsDomainNamePatch successfully', function(done) {
        //uncomment below and update the code to test v4DomainsDomainNamePatch
        //instance.v4DomainsDomainNamePatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4DomainsGet', function() {
      it('should call v4DomainsGet successfully', function(done) {
        //uncomment below and update the code to test v4DomainsGet
        //instance.v4DomainsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4DomainsPost', function() {
      it('should call v4DomainsPost successfully', function(done) {
        //uncomment below and update the code to test v4DomainsPost
        //instance.v4DomainsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
