/**
 * SMTP Public API overview
 * SMTP.com Public API v4
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: support@smtp.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SmtpPublicApiOverview);
  }
}(this, function(expect, SmtpPublicApiOverview) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SmtpPublicApiOverview.ReportsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ReportsApi', function() {
    describe('v4ReportsGet', function() {
      it('should call v4ReportsGet successfully', function(done) {
        //uncomment below and update the code to test v4ReportsGet
        //instance.v4ReportsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4ReportsOndemandPost', function() {
      it('should call v4ReportsOndemandPost successfully', function(done) {
        //uncomment below and update the code to test v4ReportsOndemandPost
        //instance.v4ReportsOndemandPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4ReportsPeriodicPost', function() {
      it('should call v4ReportsPeriodicPost successfully', function(done) {
        //uncomment below and update the code to test v4ReportsPeriodicPost
        //instance.v4ReportsPeriodicPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4ReportsPeriodicReportIdDelete', function() {
      it('should call v4ReportsPeriodicReportIdDelete successfully', function(done) {
        //uncomment below and update the code to test v4ReportsPeriodicReportIdDelete
        //instance.v4ReportsPeriodicReportIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4ReportsPeriodicReportIdPatch', function() {
      it('should call v4ReportsPeriodicReportIdPatch successfully', function(done) {
        //uncomment below and update the code to test v4ReportsPeriodicReportIdPatch
        //instance.v4ReportsPeriodicReportIdPatch(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v4ReportsReportIdGet', function() {
      it('should call v4ReportsReportIdGet successfully', function(done) {
        //uncomment below and update the code to test v4ReportsReportIdGet
        //instance.v4ReportsReportIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
